export const APP_VERSION = "3.47";

// Changelog (newest first)
// 3.47 - 🎨 Portrétová kartotéka: každá vestavěná postava se JEDNOU namaluje v pohádkovém stylu (celá postava podle fotek a kanonického popisu) a kreslení scén dostává tento hotový portrét místo fotky — stejná podoba a velikost postav v každé pohádce (konec „jednou vyšší, jednou menší“) a méně opravných překreslení = levnější pohádky; náhled kartotéky na /api/portraits (?redraw=<id> namaluje postavu znovu)
// 3.46 - 👫 Eva a Jakob jsou vestavěné postavy s fotkami (na všech zařízeních, s kanonickým popisem vzhledu — konzistence jako u rodiny); 🇩🇰 Andersenovy dánské pohádky ve výběru světů (Malá mořská víla, Malenka, Cínový vojáček, Divoké labutě, Slavík, Létající kufr + stávající 4) — válec je rozdělený na skupiny 🇨🇿 České a klasické / 🇩🇰 Andersen; válec vylepšen: krajní položky jdou dorolovat do středu a jsou čitelné (větší odsazení, jemnější náklon a mlžení)
// 3.45 - OPRAVA věčného „Píšu… (2. pokus)": dlouhá pohádka (alternativní konce, hodně stránek) se nevešla do 5min limitu serverové funkce a po restartu se psala znovu OD NULY — pořád dokola; teď se rozepsaný text každých 20 s ukládá a po restartu psaní NAVÁŽE přesně tam, kde skončilo (Claude pokračuje v rozepsané odpovědi), takže se každá pohádka vždy dopíše
// 3.44 - OPRAVA konzistence „všude a pořád": kontrola desatera běží na serveru (platí pro všechna zařízení), ale měla tři díry — (1) když samotná kontrola selhala (přetížení), obrázek prošel BEZ prohlídky → teď se kontrola opakuje až 3×; (2) utržená odpověď kontroly prošla jako „ok" → teď JSON režim s velkým limitem; (3) po neúspěšných opravách se posílal vadný obrázek → teď 2 korekce + 1 čerstvé překreslení a drží se NEJLEPŠÍ ověřený pokus; kontrolu dělá silnější model (gemini-2.5-flash) a kartotéka postav se jí předává celá (8 000 znaků místo 4 000)
// 3.43 - 🧒 Postavy jako rolovací válec (jako světy): tlačítko „Vybrat postavy" ukazuje vybraná jména, uvnitř válce se postavy zaškrtávají oranžovými ✓ (vícero najednou, vlastní postavy s fotkou a ×); „+ Vlastní postava" zůstává tlačítkem pod válcem; pole se zadáním pohádky je výrazně větší (významná součást formuláře)
// 3.42 - Velký editor sedí u horního okraje displeje (pod ním zůstává místo na klávesnici) a tlačítka ✨ Rozvinout / ✕ Zrušit jsou prohozená (Rozvinout vlevo)
// 3.41 - Popis vlastního světa se píše ve stejném velkém editoru přes celý displej jako zadání pohádky (ťuknutí do pole ho otevře, ✕ Zrušit vrátí původní text); obě hlavní pole na vyplnění (zadání pohádky, popis světa) mají tenkou oranžovou linku; psané pole se zvedá VÝŠE nad klávesnici (do horní pětiny obrazovky, s větší rezervou)
// 3.40 - Zjednodušení: hlas vypravěče se vybírá AUTOMATICKY podle jazyka prostředí CZ/EN (tlačítka hlasu zmizela); tlačítko Přeložit odstraněno — pohádka se píše v jazyce prostředí bez ohledu na jazyk zadání (appka si to přebere sama); podtitul bez zmínky o tatínkově hlasu; 🎬 úvodní obrazovka při otevření appky: pokaždé jiný pohádkový motiv (vesmír, džungle, moře…), nadpis, verze a slogan „Svět pohádek podle vašich přání" — sama zmizí, ťuknutím se přeskočí
// 3.39 - Pod přepínačem 🌐 CZ|EN je malý popisek „přeložit text pohádky", aby bylo na první pohled jasné, co přepínač dělá (ve formuláři i ve velkém editoru)
// 3.38 - 🌐 Přeložit je skutečný přepínač s jezdcem (jako CZ/EN nahoře): oranžový jezdec stojí na jazyku, kterým je text napsaný, ťuknutím přejede na druhou stranu a text se přeloží — ve formuláři i ve velkém editoru
// 3.37 - 💰 Spotřeba přehledněji: čtyři karty se statistikami — 📚 počet pohádek, 📱 kolik zařízení tvořilo, 🎨 obrázky s cenou v Kč, 🎙️ namluvené znaky; každé zařízení dostává anonymní ID, takže po nasdílení uvidíte, kolik lidí appku používá (počítá se u nově vytvořených pohádek)
// 3.36 - 🔟 Desatero konzistence (DESATERO-KONZISTENCE.md): vizuální kontrola projíždí 10 pravidel — počet lidí, každý právě jednou, vlasy postavu po postavě, oblečení na správné postavě, jednotné oblečení scény, proporce, anatomie, klíčové předměty, žádný text — a vadný obrázek se překreslí až 2×; 🔀 návrat k rozbočce: tlačítko „Druhý konec" ve čtečce (i ve sdíleném odkazu a offline souboru) vrátí pohádku k výběru; Přeložit správně pozná anglický text s českými jmény (skutečný toggle)
// 3.35 - 🌐 Přeložit funguje jako toggle do opačného jazyka, než kterým je text napsaný (česky → EN, anglicky → CZ) — tlačítko ukazuje směr („Přeložit → EN")
// 3.34 - 🌐 Přeložit místo Smazat text: zadání se přeloží do jazyka vybraného vypravěče (pro anglickou pohádku do angličtiny, jména zůstávají) — ve formuláři i ve velkém editoru; mazání textu má nově oranžový ✕ přímo v rohu textového pole
// 3.33 - OPRAVA zasekávání psaní s vloženým PDF: velký dokument se při psaní četl celý a pohádka se nevešla do časového limitu („Píšu… (3. pokus)") — PDF se teď JEDNOU shrne do podkladu (místa, jména, data, program), který se uloží k pohádce; psaní pak běží rychle a případný restart už PDF znovu nečte
// 3.32 - OPRAVA rozhozeného formuláře po vložení PDF: dlouhý název souboru roztahoval kartu (a s ní celou stránku do šířky) — název se teď zkracuje trojtečkou a karta drží šířku formuláře
// 3.31 - Appka se při psaní už nezvětšuje/nezmenšuje: klávesnice stránku jen překryje (nemění její velikost) — viditelnost psaného pole dál zajišťuje automatický posun nad klávesnici
// 3.30 - OPRAVA přiblížené appky: fokus pole s malým písmem spouštěl auto-zoom celé stránky, který se nevracel (proto „ujíždění" editoru i posunutý jazykový přepínač) — všechna pole mají min. 16px písmo a viewport zoom zakazuje; velký editor navíc zamyká stránku pod sebou a je vyjmutý z posunu pod klávesnicí
// 3.29 - ✨ Rozvinout vychází i z vloženého PDF (hlavní zdroj: konkrétní místa, jména, data a program z dokumentu) a z aktuálně vybraného světa — respektuje přepínač použití PDF; tlačítka editoru zpět na plnou velikost (64 px, stejná); jazykový toggle vpravo nahoře s oranžovým jezdcem
// 3.28 - Tlačítka ve velkém editoru přání jsou přesně stejně velká (pevná výška 54 px, text na jeden řádek)
// 3.27 - Odstraněno dvojité Zrušit u přidávání postavy/světa: chip nahoře zůstává „+ Vlastní postava/svět" (jen se zvýrazní), rušení má jen jedno oranžové tlačítko v panelu
// 3.26 - Vlastní postava může mít až 5 fotek (lepší podoba tváře na obrázcích — fotky jdou do psaní i kreslení); velký editor přání: 4 stejně velká tlačítka v mřížce (✕ Zrušit, 🧹 Smazat, ✨ Rozvinout, ✓ OK); přepínač jazyků CZ/EN jako velký toggle s jezdcem
// 3.25 - Vložené PDF jako hezká karta: světlý název, popisek stavu, přepínač „použít v pohádce" (PDF zůstane nahrané, jen se dočasně vypne) a oranžové ✕ pro odebrání
// 3.24 - Velký editor přání má oranžové ✕ Zrušit — zavře okno a vrátí text do podoby před otevřením (OK změny nechá, 🧹 maže)
// 3.23 - Jednotné tlačítko Zrušit napříč aplikací: oranžové s křížkem (✕ Zrušit) — v potvrzovacích oknech, u přidávání postavy/světa i u okna s odkazem na poslanou pohádku
// 3.22 - PDF inspirace až 10 MB (větší soubory jdou rovnou do úložiště — dřív končily na limitu 3,5 MB, tlačítko ukazuje ⏳ při nahrávání); systémové hlášky (alert) nahrazeny stylovým oknem appky s tlačítkem OK
// 3.21 - Oblečení podle počasí KONKRÉTNÍ SCÉNY: šatník má venkovní a vnitřní variantu (venku bundy, uvnitř sundané) a všechny postavy v jedné scéně jsou oblečené stejně — nikdo nabalený vedle někoho v tričku (hlídá i vizuální kontrola); nadpis výběru pokračování je bílý (byl tmavý); výběr konce se už neukazuje mimo čtečku (plaval nad formulářem)
// 3.20 - Náhled pozadí předělán: žádná oka — PODRŽENÍM světa se ukáže malá karta s ilustrací, která se plynule roztáhne na celý displej; puštěním se náhled zavře, ťuknutím svět vyberete (nápověda přímo v nabídce)
// 3.19 - Výběr pozadí: náhled 👁 je u KAŽDÉHO světa (ťuknutí vybere pozadí a ukáže ho přes celý displej) a nabídka má záhlaví s oranžovým ✕ — křížek pro odchod mají teď všechny rolovací nabídky
// 3.18 - Oranžový vycentrovaný křížek ✕ u všech rozbalených panelů; výběr světa je sbalený za tlačítkem „Vybrat svět" a má stejný ✕; v nabídce pozadí nová položka 👁 Ukázat celé pozadí — schová všechna tlačítka, ťuknutí kamkoli vrátí zpět; velký editor přání: světlejší podklad a vynucený bílý text
// 3.17 - Text ve velkém editoru přání je bílý (byl příliš tmavý na tmavém pozadí), světlejší i kurzor a nápověda
// 3.16 - Přejmenováno na „Alternativní konce"; popisek přepínače zůstává bílý i po zapnutí; rozbalené rollery (ponaučení, klasické pohádky) mají křížek ✕ — jdou zavřít i bez výběru
// 3.15 - Svět pohádky jako 3D roller (vestavěné světy; vlastní světy a Vlastní svět zůstávají tlačítka, první položka „Bez světa"); Dva konce jako klasický přepínač zleva doprava; Přání & inspirace se po ťuknutí otevře ve velkém okně přes displej — celý text viditelný, mazání i OK po ruce
// 3.14 - Rozepsané zadání pohádky se neztratí: text v poli Přání se průběžně ukládá do telefonu a přežije aktualizaci appky i přepnutí do jiné aplikace; smaže se tlačítkem 🧹
// 3.13 - Dva konce a Vybrat ponaučení jsou tlačítka přes celou šířku (jako Hudba); rolovací seznamy (ponaučení, klasické pohádky) mají 3D roller efekt — položky se při rolování naklápí jako na válci
// 3.12 - Logika počasí: postavy se v zimě/na horách obléknou (bunda, čepice, šála, sněhule), v horku odlehčí (kraťasy, sandály, plavky), v dešti pláštěnky — vždy přes zamčený Story outfits (stejný převlek ve všech scénách, bundy nemizí), postavy zůstávají rozpoznatelné podle svých barev; vizuální kontrola hlídá, že převlek na obrázku opravdu je
// 3.11 - 🪄 Rozvinout: nové tlačítko u pole přání — z pár slov („legendy z historie Benátek…") AI rozepíše detailní osnovu (pojmenované postavy, místa, letopočty, kostýmy, zápletka), kterou si před generováním můžete upravit; větší tlačítko ▶ u uložených pohádek (58 px — pohodlně se trefí)
// 3.10 - Diagnostika přímo v appce: když se psaní opakuje, řádek pohádky ukazuje číslo pokusu („✍️ Píšu… (2. pokus)") a žlutě POSLEDNÍ CHYBU, kvůli které předchozí pokus spadl — konec hádání, co se děje
// 3.09 - Konec maskovaných chyb při psaní: restart jobu dřív smazal chybovou hlášku (věčné „Píšu…") — teď se chyba přenáší dál a po 3. neúspěšném pokusu se pohádka zastaví s viditelnou příčinou; nová diagnostika /api/job/list ukáže stav a chyby všech jobů
// 3.08 - OPRAVA zasekávání ve fázi „Píšu…": dlouhý scénář (hlavně dva konce ≈ 16+ scén) se nestreamovaný nevešel do 250s limitu jednoho pokusu — psaní teď STREAMUJE (text přitéká průběžně, žádný útes) a job posílá heartbeat i během psaní, takže se neukazuje falešné ⚠ zaseknutí
// 3.07 - Výběr konce předělán na dvě velké grafické karty: obrázek první scény každé cesty + popisek (jasně vidět, kam která vede) — v appce, ve sdíleném odkazu i v offline souboru; OPRAVA: Claude vrací konce v novém jednoznačném formátu (endingA/endingB) — dřív se větev občas zahodila a tlačítka se vůbec neukázala (otázka zůstala jen v textu)
// 3.06 - Dva konce vylepšeny: rozdvojení přichází v ~2/3 příběhu (ne až před poslední stránkou) a každý konec má aspoň 2–4 plnohodnotné scény; poslední společná scéna KONČÍ hlasovou otázkou se jmenováním obou cest a pohádka se zastaví, dokud dítě nevybere (tlačítka se ukážou po dovyprávění otázky); oprava: výběr konce se neztratil při otevření hotové pohádky z řádku jobu ani při doplnění chybějících obrázků
// 3.05 - 🔀 Pohádka se dvěma konci: přepínač „Dva konce (na výběr)" ve formuláři (defaultně vypnuto, před generováním se potvrzuje) — vypravěč na konci společného děje položí otázku a čtenář vybere ze dvou tlačítek, jak pohádka skončí; oba konce se předgenerují (obrázky i hlas), takže druhý večer jde vybrat ta druhá cesta; funguje ve čtečce, ve sdíleném odkazu i v offline souboru
// 3.04 - Offline soubor s pohádkou předělán na čtečku jako v appce: obrázek přes celý displej, text v čitelném pruhu dole (bílá na tmavé), velká viditelná tlačítka ← ▶ →; na šířku se schová titulek, ať má obrázek maximum místa; větší tlačítka u uložených pohádek (Pokračování/Poslat/Soubor + koš) — na tabletu se lépe trefují
// 3.03 - 💾 Pohádka jako soubor: u uložené pohádky tlačítko Soubor — zabalí obrázky, text i namluvení do jednoho HTML souboru s přehrávačem; pošlete ho Quick Share/Bluetooth BEZ internetu a příjemci se přehraje offline (bez platnosti 90 dní)
// 3.02 - Pohádky jsou ~5× menší: nové obrázky se ukládají jako WebP místo PNG (15 stránek ≈ 5–8 MB místo 25+ MB — méně místa v telefonu, rychlejší stažení i poslání); starší uložené pohádky zmenší telefon automaticky při posílání
// 3.01 - OPRAVA posílání pohádky: obrázky se nahrávají rovnou z prohlížeče do úložiště (binárně) — velké scény přes server narážely na limit 4,5 MB na request a nahrávání se točilo dokola; po chybě naváže další pokus tam, kde skončil (nenahrává od začátku); 2 pokusy na soubor a případná chyba se ukáže i s důvodem
// 3.00 - Poslat pohádku v2: nahrávání ukazuje průběh (⏳ 3/15), jede 3 scény najednou (rychlejší) a po dokončení se otevře okno s odkazem a tlačítky Sdílet… / Kopírovat — sdílecí nabídka Androidu se dřív po dlouhém nahrávání nesměla otevřít (vyžaduje čerstvé ťuknutí), proto to vypadalo, že se nic nestalo
// 2.99 - 📤 Poslat pohádku: u uložené pohádky tlačítko Poslat — nahraje obrázky i namluvení a pošle odkaz (WhatsApp, e-mail…) na přehrávací stránku, příjemce nic neinstaluje (odkaz platí 90 dní); OPRAVA konzistence vymyšlených postav: úprava promptu měla nízký strop a ořezávala popisy postav na konci (jednou blond, podruhé hnědé) — zvednuto + pojistka, vizuální kontrola čte celou kartotéku a hlídá barvu vlasů postavu po postavě, vymyšlení lidé musí mít popis stejně přísný jako hrdinové
// 2.98 - 💡 Ponaučení pohádky: rolovací výběr 13 ponaučení (pomáhat druhým, nevzdávat se, mluvit pravdu…) — vplete se přirozeně do děje, bez kázání; 📖 Pokračování: u každé uložené pohádky tlačítko ✨ Pokračování — nový díl naváže na minulý děj, hrdinové si pamatují, co zažili (obnoví se i obsazení a svět); 🎲 námět obojí respektuje
// 2.97 - Klávesnice na tabletu podruhé: appka si sama změří výšku klávesnice (visualViewport) a psané pole posune NAD ni — funguje i v prohlížečích, které klávesnicí obsah překrývají (Samsung Internet, WebView)
// 2.96 - Oprava psaní na tabletu: otevřená klávesnice stránku zmenší místo překrytí (interactive-widget) a pole, do kterého píšete, se samo posune do viditelné části obrazovky
// 2.95 - Stylové potvrzovací okno appky místo systémových dialogů (mobilní data, zrušení/nakopnutí pohádky); OPRAVA konzistence vymyšlených postav: zámek vzhledu omylem vyhazoval postavy z příběhu (Otesánek…) — teď v něm zůstávají a Claude jim musí psát plný popis (co to je, barvy, velikost) → stejná podoba na všech stránkách
// 2.94 - Panel 💰 Spotřeba nově počítá Gemini a hlas: appka si po každé pohádce zapíše počet obrázků a znaků (usage/ v Blobu) — „🎨 Gemini: N obrázků ≈ $ ≈ Kč" a „🎙️ Namluveno ~N znaků" za 30 dní; ElevenLabs kredity se ukážou po povolení oprávnění User→Read u API klíče
// 2.93 - Panel čtečky vyjíždí zpoza spodní hrany (na výšku) / pravé hrany (na šířku) s plynulým efektem — obraz se už nezmenšuje; mazání: po odjištění zmizí vlastní 🗑️ a ▶ (konec dvou košů) + nápověda „přejeďte doleva pro smazání"
// 2.92 - Pozadí v2: každý svět je celá nová ilustrace s Nicoláskem a Valentýnkou (podle fotek), stará grafika se skryje; výběr světa velkým tlačítkem s rolovací nabídkou; ovládání čtečky nikdy nepřekryje obrázek (při otevření panelu se obraz plynule zmenší); ikona otočení = ležatý/stojící telefon; hudební podkres se ztiší pod hlasem a vrací se mezi scénami (ducking)
// 2.91 - Ovládání čtečky předěláno: jen 4 velká tlačítka (Přehrát/Pauza, Strana, Na šířku, Domů) — v portrétu jedna řada na šířku obrázku dole, ve fullscreenu jeden sloupec na výšku obrázku vpravo; tlačítka Hlas a Hudba se nastavují v hlavním menu, auto-přechod scén je zapnutý vždy
// 2.90 - Ovládání čtečky je decentní: kompaktní tmavý panel (na výšku dole ve 2 sloupcích, na šířku úzký sloupek u kraje), nepřekrývá obrázek, objeví se jen ťuknutím na displej a po 5 s sám zmizí
// 2.89 - Oprava swipe mazání: po swipu už se omylem nespustí pohádka (potlačení syntetizovaného kliku, stav v ref); odjištěná položka má neprůhledné pozadí — červené Smazat neprosvítá skrz text
// 2.88 - Vision QA: každý vygenerovaný obrázek automaticky zkontroluje kontrolní model (dvojitá postava, cizí lidé, špatné vlasy/oblečení, anatomie) a vadný se JEDNOU překreslí s popisem chyby; do zámku přidáno „každá postava přesně jednou" (konec dvou tatínků)
// 2.87 - Nový ovládací panel čtečky: moderní tlačítka přes celou šířku s popiskem (Přehrát, Auto, Hlas, Hudba, Na šířku, Domů — viditelné i na výšku, panel jde rolovat); otočení jedním ťuknutím (tlačítko se řídí skutečným stavem fullscreenu); Domů vždy ukončí fullscreen — home screen už nebude obrovský na šířku
// 2.86 - Displej při čtení pohádky nezhasíná (Wake Lock — drží se, dokud je otevřená čtečka, obnoví se po návratu do appky); rolující titulky: začátek i konec věty jsou plně čitelné (vnitřní odsazení textu větší než vyblednutí okrajů)
// 2.85 - Hlubší a dramatičtější příběhy (přímá řeč ve scénách, pocity hrdinů, skutečná sázka, temný okamžik před rozuzlením); dlouhé názvy v Posledních pohádkách rolují tam a zpět (čitelné celé); stylové mazání: swipe doleva nebo ťuknutí na 🗑️ odhalí červené Smazat — konec systémového dialogu
// 2.84 - Pravidla konzistence (PRAVIDLA-KONZISTENCE.md): vzhled postav je KANONICKÝ — po napsání příběhu se popis vzhledu serverově přepíše doslovnými popisy z kartotéky (konec „jednou blond, podruhé hnědé"); převleky jen přes zamčený záznam Story outfits; anatomie natvrdo (přesně 2 ruce, 2 nohy, 5 prstů, kolo má 2 kola)
// 2.83 - Inspirační fotky u pole přání (📷 Foto) zvednuty ze 3 na 8 — sjednoceno s fotkami vlastního světa
// 2.82 - Vlastní svět pohádky unese až 8 fotek (dřív 1): mřížka náhledů s mazáním ×, vícenásobný výběr najednou, všechny fotky jdou Claudovi jako inspirace; staré světy s jednou fotkou fungují dál
// 2.81 - Konzistence a kvalita obrázků: primární malíř zpět gemini-3.1-flash-image (2.5 jen záloha při kvótě); styl natvrdo 2D malovaná ilustrace (zákaz 3D renderu, fotorealismu i podpisů); sportovní vybavení (kolo!) a sportovní oblečení se zamyká jako Key object — stejný typ, barvy i dres v každé scéně
// 2.80 - Příběhy píše Claude Sonnet místo Opusu (kvalita pohádek srovnatelná, ~5× levnější psaní); jde přebít proměnnou ANTHROPIC_MODEL_PRIMARY
// 2.79 - Levnější kreslení: primární obrázkový model je gemini-2.5-flash-image (~0,90 Kč/obrázek, −42 %), dražší gemini-3.1-flash-image (~1,55 Kč) zůstává jen jako záloha při vyčerpání denní kvóty; jde přebít proměnnou GEMINI_IMAGE_MODEL_PRIMARY
// 2.78 - Strop automatických oživení: pohádka bez posunu se oživí max 4×, pak se zastaví s chybou („zastaveno, ať se nepálí kredit") — každé oživení překresluje scény a stálo peníze; posun vpřed počítadlo nuluje
// 2.77 - Ochrana denní kvóty Gemini (1000 obrázků/den/model): při stropu se pokusy neopakují, automaticky se zkusí záložní model (gemini-2.5-flash-image → kapacita 2×), a když je na stropu i ten, pohádka se okamžitě zastaví s jasnou chybou; nakopnutí po resetu naváže na hotové scény (nepíše ani nekreslí znovu)
// 2.76 - Když Gemini nekreslí (vyčerpaná kvóta, billing…), appka ukáže důvod přímo pod tlačítkem („🎨 Obrázky hlásí chybu: Gemini 429…") místo věčných přesýpacích hodin; pohádka bez jediného obrázku skončí viditelnou chybou, ne prázdnou knížkou
// 2.75 - Křížek ✕ v rohu dílů tlačítka fronty: zaseknutou/chybovou pohádku zruší jedním ťuknutím (smaže i data na serveru); zdravě běžící se 1× zeptá, ať ji děti nezruší omylem
// 2.74 - 📜 České pohádky: rolovací seznam 28 licenčně volných klasik (lidové, Erben, Němcová, Grimmové, Andersen, Perrault) — vybraná pohádka funguje jako svět, příběh se odehraje s vašimi hrdiny; 🎲 námět i auto pozadí ji respektují
// 2.73 - Aplikace se otevírá vždy do hlavního menu — rozečtená pohádka už nenaskočí přes celou obrazovku, zůstává načtená pod formulářem (▶ ji otevře ve čtečce)
// 2.72 - 🎲 Vymysli námět respektuje vybraný svět pohádky a zaškrtnuté postavy (a staví na už napsaném textu); u vlastního světa nové tlačítko 🧠 Nastuduj svět — z popisu nebo vloženého internetového odkazu Claude sestaví průvodce světem (postavy, vzhled, atmosféra), a když mu něco chybí, položí doplňující otázku
// 2.71 - Pod počtem stránek se ukazuje orientační délka čtení: „🕐 cca X min čtení (1 stránka ≈ půl minuty)", přepočítává se hned při změně počtu
// 2.70 - Počet stránek se místo posuvníku (šlo o něj omylem zavadit) nastavuje tlačítky − a + po stranách čísla; drží meze 3–20
// 2.69 - Tlačítko 🧹 Smazat text u pole přání (objeví se, jen když v poli něco je); živější přednes hlasu (voice_settings: víc intonace a dramatičnosti); zvířecí zvuky se píší foneticky a protaženě („Haf haf!“, „Mňauuu…“), ať je vypravěč zahraje; česká výslovnost jmen — do TTS jde Nikolásek/Džejms/Árčí (titulky zůstávají s původním pravopisem)
// 2.68 - Pozadí aplikace jsou teď ilustrace ve stylu pohádek: maluje je Gemini (stejný styl jako obrázky scén), každý z 9 světů se vygeneruje jen jednou a uloží na server (backgrounds/); než se stáhne, drží barevný gradient z v2.67
// 2.67 - Přepínatelné pozadí aplikace: 9 světů (noc, les, hory, vesmír, džungle, moře, závody, pouť, kouzlo) malovaných v CSS; tlačítko 🎨 vlevo nahoře jimi roluje, režim Auto přepne pozadí samo podle zvoleného tématu pohádky (vlastní svět = ✨ kouzlo); volba se pamatuje
// 2.66 - Anglické názvy postav v EN verzi (Dad Jan, Mom Jana, Archie the dog…) v chipech i vyprávění; tlačítko 🎲 Vymysli námět (Claude navrhne zápletku do pole přání); vlastní svět pohádky podle fotky nebo popisu — chip „+ Vlastní svět", uložené světy se dají znovu použít i smazat
// 2.65 - Titulky na šířku: text jede synchronně s hlasem (řízeno pozicí v nahrávce, pauza text zastaví), vnitřní okraje rámečku + měkké vyjíždění textu na krajích; rámeček zůstává na šířku obrázku
// 2.64 - Oprava: dlouhý název pohádky vytlačoval tlačítka 🗑️ a ▶ mimo displej (grid minmax(0,1fr) + zkrácení názvu trojtečkou)
// 2.63 - Mazání pohádek z historie: ikona 🗑️ u každé položky (s potvrzením) — smaže pohádku z telefonu vč. offline dat a uvolní místo
// 2.62 - Věrnější táta Jan: nová detailní fotka obličeje jako druhá reference pro Gemini + přesnější popis (vysoké čelo, krátké tmavě hnědé vlasy, strniště, hnědé oči); podpora více referenčních fotek na postavu
// 2.61 - Oprava „blob-write-failed: invalid header value": Blob token se čistí (uvozovky, nové řádky, smetí z Quickstartu) — z hodnoty se vytáhne jen samotný vercel_blob_rw_… token
// 2.60 - Server už nehromadí hotové pohádky (jsou v telefonu): po stažení se serverová data pohádky mažou okamžitě, úklid chrání jen běžící joby (+1h lhůta), běží 1× za hodinu — bezplatný 1GB Blob se už nezaplní; důvod selhání startu se zobrazí (Server: blob-write-failed…)
// 2.59 - Diagnóza mrtvých startů: start jobu zapíše stav SYNCHRONNĚ — když Blob zápis selže (plné úložiště / token), vrátí se viditelná chyba místo zombie jobu; úklid úložiště běží i při startu aplikace (1× za 6 h) a maže osiřelé joby starší 3 h
// 2.58 - Záchrana zaseknutých pohádek: job, který na serveru nikdy nezapsal stav (404), se automaticky oživí přes /continue nebo po 5 min ukončí chybou; zaseknutý díl tlačítka červeně pulzuje s ⚠️ — ťuknutím nakopnete, podruhé odeberete z fronty
// 2.57 - Offline zásoba rozšířena na 20 pohádek (localStorage/IndexedDB/Blob drží posledních 20; žádost o trvalé úložiště, ať prohlížeč cache nemaže); upozornění před generováním na mobilních datech (~30 MB, potvrzení 1× za sezení)
// 2.56 - Ťuknutí na díl tlačítka (1./2./3.) přepne kartičky na průběh té konkrétní pohádky; zvolený díl je zvýrazněný bílým rámečkem
// 2.55 - Fronta bez bublinek: velké tlačítko se rozdělí na části — jedna část na pohádku (✍️ píše se / 🎨 x/y s plnícím se pruhem / ▶ Otevřít / ⚠️ chyba); plovoucí bublinky z hlavní obrazovky zmizely
// 2.54 - Oprava zaseknutého „Píšu novou pohádku": kratší imagePrompty (popis postav se do obrázků vkládá automaticky, nekopíruje se 20×) → psaní 20stránkové pohádky se vejde do 5min limitu; retry při zahlcení Claude API (429); popisek, že kartičky ukazují nejnovější pohádku
// 2.53 - Při čtení pohádky se neukazují bublinky průběhu dalších pohádek — průběh a tlačítko Otevřít uvidíte po návratu Domů
// 2.52 - Čtečka na PC a tabletu přes CELOU obrazovku (zrušen limit šířky 860 px v reader módu; formulář zůstává úzký)
// 2.51 - Oprava Spotřeby: částky z Anthropic API jsou v centech (ukazovalo 100× víc), přepočet na Kč kurzem ČNB; srozumitelná hláška, když ElevenLabs klíč nemá oprávnění číst účet
// 2.50 - Chybová hláška jde zavřít křížkem ✕ (dřív zůstávala až do dalšího pokusu)
// 2.49 - Přehled 💰 Spotřeba: skutečná útrata za Claude (Admin API, celý účet, posledních 30 dní) a stav kreditů ElevenLabs přímo v aplikaci; Gemini jen odkazem (Google útratu přes API nevydává)
// 2.48 - Spolehlivější start serverové výroby (fronty): 2 pokusy s timeoutem 30 s místo jednoho s 15 s, server odpovídá okamžitě (zápis zadání do Blobu až po odpovědi) — méně pádů do lokálního generování bez fronty
// 2.47 - Automatický úklid Blob úložiště: po dokončení pohádky se smažou serverová data jobů, které vypadly z historie posledních 10 pohádek (běžící a čerstvé joby <24 h se nikdy nemažou)
// 2.46 - Fronta pohádek: až 3 pohádky se připravují najednou na serveru — další jde zadat hned, bez čekání; každá má vlastní řádek s průběhem a tlačítkem Otevřít, kartičky ukazují tu nejnovější
// 2.45 - Až 20 stránek: navazovací serverový job (po 5min limitu Vercelu automaticky pokračuje endpointem /api/job/continue — zdarma, bez Pro plánu); delší příběhy od Clauda (16k tokenů); rychlejší načtení — hotové scény se stahují do telefonu průběžně už během výroby a kartičky ukazují skutečné náhledy
// 2.44 - Fix „nabídka zmizela": rozepsaný draft bez obrázků už neotevře prázdnou temnou čtečku (obnova jen s kompletními obrázky + pojistka: čtečka bez pohádky → návrat na formulář); stažení hotové pohádky ze serveru s retry a placeholderem; otevřený panel ovládání už nepřekrývá toast průběhu
// 2.43 - Serverové generování na Vercelu: pohádka se připraví na serveru (Blob), telefon jen sleduje stav a stáhne výsledek — přepnutí appky nevadí; bez Blob tokenu automatický fallback na lokální generování
// 2.42 - Kotevní obrázek: scéna 1 se generuje první a její obrázek je vizuální referencí pro všechny další scény — postavy, výšky, styl i předměty (auto) se kopírují z ní
// 2.41 - Animace „Píšu příběh": píšící tužka ✍️, blikající tečky, výraznější a rychlejší shimmer
// 2.40 - Key objects lock (auto a předměty stejné v celé pohádce); tlačítko 🔄 Na šířku v panelu (fullscreen + orientation lock)
// 2.39 - Konzistence velikostí: povinné 'Heights:' v popisu postav, lock na věk/proporce, sanitizér zachovává výšky; fallback prompt pro blokované scény; poctivý toast při chybějících obrázcích
// 2.38 - Anti-stuck: Wake Lock (displej nezhasne při generování), hlídač zaseknutí (2,5 min bez pokroku → tlačítko Pokračovat), auto-obnovení při návratu do zamrzlé záložky
// 2.37 - Odolné generování: job se pamatuje (text i obrázky), auto-resume po restartu; průběžné cachování scén; až 3 verifikační kola — pohádka není hotová, dokud nejsou všechny obrázky
// 2.36 - Nové referenční postavy: James (6, nejlepší kamarád z Riverside) a Bella (8, Jamesova sestra) s fotkami
// 2.35 - Rodinné referenční fotky: táta Jan, máma Jana, pes Archie (nová postava), Valentýnka — Gemini nyní dostává fotky a kreslí podle skutečné podoby
// 2.34 - Panel přikotven dole; šipky integrované do obrázku (střed, jeho okraje); Recent stories přesunuty pod pohádku
// 2.33 - Anglické názvy témat (Story world) při EN; vlastní postavy se ukládají (localStorage) — zůstávají do smazání ×, pohádky s nimi zůstávají v historii
// 2.32 - Jednotná velikost obrázků: Gemini generuje 16:9 (imageConfig), zobrazení v pevném 16:9 rámu (cover) v obou orientacích
// 2.31 - Portrait reader: text box přímo pod obrázkem, ovládací panel pod textem (jako v landscape); toggle panelu ťuknutím kamkoli na kartu
// 2.30 - Hudba defaultně vypnutá; titulky ukazují skutečné modely (API /api/models); mluvené „Dobrou noc, Nicolásku a Valentýnko" na konci titulků
// 2.29 - Přepínač jazyka UI 🇨🇿/🇬🇧: celé rozhraní česky nebo anglicky, volba se pamatuje, EN auto-vybere anglického vypravěče
// 2.28 - Text na bílém podkladu: portrait celý text bez rolování, landscape bílý jednořádkový ticker
// 2.27 - Ticker jen pod šířkou obrázku; play z hlavní obrazovky → reader mód; replay z historie auto-přehraje; manifest bez orientation (rotace dle systému)
// 2.26 - Fix hlas (payload bez obrázku + odblokování play); šipky skryté i v portrait (jen s panelem); play zavře panel + restart rollingu; PWA manifest (fullscreen po přidání na plochu)
// 2.25 - Automatická přestavba při otočení: layout + restart rolování textu (portrait ⇄ widescreen)
// 2.24 - Widescreen: bez nadpisu, text = jednořádkový horizontální ticker dole, šipky jen s panelem (odsazené); obraz ~90 % výšky
// 2.23 - Titulky v malém okně POD obrázkem (nepřekrývají obraz), auto-rolling; panel dole (portrait) / vpravo (landscape); fix výšky v landscape
// 2.22 - Imerzní čtečka: obraz přes celý screen, text jako titulky dole (scrolluje, nikdy nepřeteče), ovládání skryté — ťuknutí zobrazí panel vpravo, šipky plovoucí po stranách
// 2.21 - Šířka: full-width obraz na mobilu, tablet/landscape = obraz vedle textu; velká tlačítka přes celý panel; vlajka hlasu (🇨🇿/🇬🇧); play už neukazuje ⏳ při přepnutí hlasu
// 2.20 - Reader: obraz bez ořezu/deformace (contain, kino styl), text scrolluje; pryč Nová pohádka; popisky pod tlačítky; auto-kontrola + oprava chybějících obrázků; 2 scény paralelně; progres i pro bg pohádku
// 2.19 - Reader mode: book vyplní viewport bez edge-to-edge; šipky ← → přesunuty pod kartu (žádné ořezání)
// 2.18 - Detekce přerušeného spojení (přepnutí appky): česká hláška + tlačítko Zkusit znovu; timeout 90s na scene fetch
// 2.17 - Odstraněn reader mode (žádný fullscreen); pohádka se zobrazí pod formulářem s auto-scroll; popis kroků generování
// 2.16 - Odstraněno expand-on-play (CSS position:fixed overlay při ▶); čistý reader mód bez přepínání
// 2.15 - Expand on play: ▶ roztáhne book přes celý viewport (CSS position:fixed, bez native fullscreen)
// 2.14 - Reader: max screen (edge-to-edge, skrytý back-btn, kompaktní titulek); konzistence postav: APPEARANCE LOCK v Gemini i Claude
// 2.13 - Tlačítko Vytvořit pohádku: animovaný progress fill + %; gen-cards pod tlačítkem; odstraněno Zpět na pohádku
// 2.12 - Odstraněn fullscreen mód; oranžové šipky ← → pro navigaci scén
// 2.11 - Gen-cards od začátku načítání; oranžové tlačítko 🏠 v ovládání; oranžové tlačítko Zpět na pohádku
// 2.10 - Fullscreen: image 16:9 (no crop), text pod ním; fix text overflow; témata: Pokémon + Sonic
// 2.9 - Reader mode: viewport-filling layout (CSS Grid 1fr na book-card), image vyplní zbývající výšku
// 2.8 - Fullscreen: tap-to-show ovládání (controls skryty, zobrazí se na klik/tap na 3s, pak zmizí)
// 2.7 - Fullscreen: CSS Grid (1fr auto auto auto) na book-card → controls vždy viditelné; 16:9 aspect-ratio v reader; audio optional
// 2.6 - Historie: výrazné karty s offline/size/scény badge, tlačítko → oranžový % bar + ikonky scén
// 2.5 - Fullscreen: obraz dostane explicitní height:65dvh (bez flex chain), draft pohádky do localStorage při přepnutí okna
// 2.4 - Fullscreen: .book dostane position:fixed inset:0 z-index:10 — bypasses flex chain, viewport height garantována
// 2.3 - Fullscreen: wrapper-div + position:absolute inset:0 pro obraz (grid 1fr nefungoval s flex-allocated height v Chrome Android)
// 2.2 - Konzistence postav: silnější Gemini prompt (zákaz extra postav, fixní vlasy+oblečení), Claude kopíruje popis doslova
// 2.1 - Fullscreen: okamžité nastavení CSS třídy (iOS + Android fix); Cache: vždy ukládat i při chybě audia; bookReady = obrazky stačí
// 2.0 - Verze badge, fix historie během bg generování, IndexedDB cache cross-session
// 1.9 - IndexedDB cache pro pohádky z historie (přežije restart PWA)
// 1.8 - Fullscreen opravy: správný flex chain, ctrl-fullscreen rozměry, aspect-ratio fix
// 1.7 - Fullscreen mód (⛶), swipe slidy, tečky uvnitř karty
// 1.6 - Paralelní generování + sledování starší pohádky, cache scén v paměti
// 1.5 - Reader mód (celá obrazovka pro pohádku), auto-fullscreen při spuštění
// 1.4 - Oprava 504 timeoutu pro 15 scén, hudební tlačítko v formuláři
// 1.3 - Rolling credits po dokončení pohádky
// 1.2 - ElevenLabs hlas, výběr vypravěče
// 1.1 - Gemini ilustrace, background music
// 1.0 - Základní verze: Claude + generování pohádek
