export const APP_VERSION = "4.26";

// Changelog (newest first)
// 4.26 - 🎚️ DOLADĚNÍ KLONOVANÉHO HLASU: appka dřív pro klonovaný rodinný hlas používala napevno stejná playback nastavení (stabilita/podobnost/styl) jako pro vestavěné hlasy, nastavitelná jen přes proměnné prostředí na Vercelu — žádná cesta, jak „plechový"/umělý zvuk klonu doladit z appky. Nové ⚙️ „Doladit hlas" u každého klonu ve výběru vypravěče: 3 posuvníky (stabilita/podobnost zdroji/styl), tlačítko „Zkusit" přehraje ukázku s ROZEHRANÝM (ještě neuloženým) nastavením přímo přes existující mechanismus ukázek, „Uložit" zapíše nastavení k danému hlasu na server — od té chvíle se použije při každém namluvení touhle konkrétní klonovanou stopou (čtení pohádky i budoucí ukázky). Výchozí hodnoty beze změny (0.42/0.8/0.35), takže nikomu nic nezmění postaru fungující hlas.
// 4.25 - 🔒 SOUHLAS PŘED KLONOVÁNÍM HLASU: appka dřív spouštěla nahrávání hlasu (biometrický údaj, i u dětí) jen s uklidňující info bublinou, bez skutečného souhlasového kroku. Teď appka před PRVNÍM nahráním vyžádá výslovné potvrzení (kdo nahrává, souhlas se zpracováním u ElevenLabs) s odkazem na novou stránku /privacy — vynuceno i na serveru (bez časového razítka souhlasu appka nahrávku nepřijme), ne jen v UI. Základní zásady ochrany soukromí zatím jako startovní návrh — před ostrým použitím je potřeba právní kontrola a doplnění konkrétních údajů provozovatele. 💰 VÝCHOZÍ HLAS TEĎ GEMINI TTS místo ElevenLabs (~4 Kč vs. ~8 Kč na pohádku) — ElevenLabs zůstává volitelný jako „Prémium" hlas a jediná cesta pro klonované rodinné hlasy.
// 4.24 - 📍 Oranžové potvrzení u tlačítka „Pohádka podle mé lokality" (viz 4.20) dřív po 1,8 s zhaslo, což šlo snadno přehlédnout. Teď zůstává oranžové trvale — zmizí, jen když se tlačítko zkusí znovu.
// 4.23 - 📏 ZAFIXOVÁNY RELATIVNÍ VÝŠKY knihovních postav napříč VŠEMI pohádkami: dřív si Claude větu "Heights:" vymýšlel nanovo v každé pohádce jen podle volného příkladu v promptu — obvykle se trefil, ale příležitostně ne (Valentýnka občas „vyrostla", protože nic nevynucovalo, že je přesně o hlavu menší než Nicolas). Nová fixní tabulka (Valentýnka nejmenší batole, o hlavu menší než Nicolas; Nicolas a James stejně vysocí; Bella o půl hlavy vyšší než oba kluci; dospělí mnohem vyšší než děti) teď PŘEPISUJE, co si Claude napsal sám, kdykoliv jsou v obsazení 2+ sledované postavy — jde i do vizuální kontroly obrázku, takže případnou chybu při kreslení appka pozná a nechá scénu předělat. Mimochodem opraveny i zbylé věkové číslovky u Jamese a Belly (porušovaly vlastní pravidlo appky „žádný číselný věk") a zpřesněn Bellin popis („slightly taller" → přesně „o půl hlavy").
// 4.22 - 📍 Tlačítko „Pohádka podle mé lokality" dřív po úspěchu neukázalo žádné potvrzení — jediná viditelná změna byl text v poli přání, což šlo snadno přehlédnout. Teď se po úspěšném návrhu tlačítko na chvíli rozzáří oranžově (✓), stejná konvence jako jinde v appce („potvrzení = oranžová"). 📋 ŽIVÝ POSTUP I PŘI PSANÍ: poslední řádek deníku (např. „píšu… 3900 znaků, 51s") se dřív zobrazoval jen během kreslení obrázků — psaní (60–200 s) tak vypadalo jako mrtvé, i když appka na pozadí reálně hlásila postup. Teď se živý řádek deníku ukazuje i během psaní.
// 4.21 - ⏱ PSANÍ 2× RYCHLEJŠÍ: Sonnet 5 bez explicitního "thinking" tiše běží ADAPTIVNÍ thinking (tichá změna oproti Sonnet 4.6, kde bez něj thinking neběžel vůbec) — a appka thinking_delta eventy ve streamu vůbec nezpracovávala, takže se to projevovalo jako neviditelný „mrtvý" čas (v testu klidně 100+ s bez jediného znaku) předtím, než začal přitékat viditelný text. Přidáno `thinking: {type: "disabled"}` na všechna textová volání Clauda (psaní příběhu i drobné pomocné dotazy) — v testu zkrátilo psaní 9scénové/4postavové pohádky ze 157–198 s na 71 s, celkový čas z ~290 s na 164 s. 🗂️ ARCHY VYPNUTY U 3+ POSTAV: napříč testy prošlo u pohádek se 3+ jmenovanými postavami jen 0/8, 0/8, 5/8, 4/8 panelů archu — ekonomika (3,5 Kč za arch skoro vždy, úspora nejistá) vychází kolem nuly nebo ztrátová. Appka teď u 3+ postav jde rovnou sólo cestou; u 1-2 postav archy zůstávají (tam prokazatelně fungují).
// 4.20 - ⏱ STABILITA A CENA GENEROVÁNÍ: jedna scéna dřív neměla vlastní strop vůči AKTUÁLNÍMU běhu funkce — ověření kvality umělo interně zkoušet 2× a při selhání ještě jednou, plus 2 kola překreslení, takže v nepříznivém případě mohla jedna scéna vyčerpat čas těsně před tvrdým 300s killem Vercelu dřív, než appka stihla předat štafetu další funkci (selfContinue). Přidán strop PRO TENTO BĚH (min. z globálního 4:40 a 260s od začátku běhu), zkrácen self-kick z 240s na 200s (víc rezervy), rozdělen 90s timeout na kreslení (60s) / text (45s) / QA kontrolu (30s) a zkráceno překreslení z 2 kol na 1 (cena/rychlost > drobná ztráta na okrajových případech). 🗂️ ARCHY (víc scén v jednom levném 4K obrázku): tolerantnější řezání mřížky (hledá nejbělejší linku v okolí místo trvání na přesné frakci), portrétové reference teď nesou popisek „jen pro PANEL X" a scény se stejným obsazením se seskupují do stejného archu — u pohádek s 3+ postavami dřív model při jednom archovém volání identity míchal/vymýšlel (0/8 prošlých panelů), po opravě 5/8 a dotažení do kompletní pohádky. Zbývá otevřená otázka, jak moc se to promítne v ostrém provozu (jednotlivé testovací běhy měly velký rozptyl) — sledovat přes debug-logs/.
// 4.19 - ⚠️ OPRAVENO falešné „zaseknuto" během zdravého psaní: appka sledovala jen done/total scén, jenže ty se během PSANÍ vůbec nehýbou (nastaví se, až je scénář hotový) — takže i naprosto zdravé psaní (běžně přes 4 minuty u delších/anglických pohádek, klidně i se zdravým restartem uprostřed, viz 📋 deník s rostoucím počtem znaků) appka po 4 minutách označila ⚠️ jako zaseknuté, přestože server žil a psal dál. Sledování teď navíc hlídá i serverový heartbeat (obnovuje se ~každých 20s, dokud Claude reálně streamuje) — ⚠️ se teď ukáže, jen když se opravdu nic neděje.
// 4.18 - 📋 DETAILNĚJŠÍ DENÍK psaní příběhu: appka dřív v „N. pokus" ukazovala jen ČÍSLO restartu, ale ne PROČ se restartuje ani co se mezitím dělo — retry pokusy Clauda (síťová chyba, přetížení, prázdný stream, i špatně naparsovaný JSON) šly jen do server konzole, kterou appka/uživatel nevidí. Teď se všechny tyhle pokusy zapisují přímo do 📋 deníku a u každého restartu je vidět délka rozepsaného textu (roste = zdravé navázání, neroste = skutečné zaseknutí, po 3× appka sama zastaví) i chyba z minulého pokusu.
// 4.17 - 💥 OPRAVENA fatální „Claude nevrátil text (prázdný stream)": appka dřív u tohohle (vzácného, ale reálného) zádrhelu na síti/serveru rovnou vzdala celou přípravu pohádky bez jediného dalšího pokusu — na rozdíl od chyby přetížení (429/529), kterou appka odjakživa zkouší znovu. Sdílená funkce pro volání Clauda teď zkouší znovu (až 3×) i prázdný stream a chybu uprostřed streamu, přesně jako už dřív dělala u přetížení — ověřeno testem proti mock serveru (prázdný stream → síťová chyba → úspěch na 3. pokus).
// 4.16 - 👤 ÚČTY: postavy, historie pohádek i nastavení jde teď přenést mezi zařízeními (mobil ↔ tablet ↔ web) — stačí jméno a heslo, žádný e-mail. Nový chip pod nadpisem appky otevře přihlášení/registraci; při registraci se rovnou uloží to, co má appka na zařízení už teď, při přihlášení na jiném zařízení se místní a účtová data BEZPEČNĚ SLOUČÍ (nikdy nic nemaže, jen přidává podle id). Appka pak na pozadí drží změny v syncu (s pár vteřinovou prodlevou). Obrázky a zvuk se nesynchronizují (ty se stejně jen dočasně cachují a při chybění se dokreslí znovu) — synchronizují se jen texty (scénáře, jména, popisy, nastavení), takže je to malé a rychlé.
// 4.15 - 📍 GPS tlačítko „Pohádka podle mé lokality" se na některých mobilech dovedlo „zaseknout" s točícím se kolečkem navěky: `getCurrentPosition` na telefonu s vypnutými systémovými službami polohy nezavolá ani úspěšný, ani chybový callback (a `timeout` parametr to některé prohlížeče ignorují) — appka teď má vlastní 15s pojistku, po které se ozve srozumitelná chyba místo věčného točení. ✨ OPRAVENO tiché OŘÍZNUTÍ u „Enrich" (rozvinutí námětu): u bohatšího/opakovaně rozšiřovaného zadání Claude narážel na strop 2000 tokenů a věta se uřízla uprostřed (viz „…Habsburg") — appka to tiše přijala jako hotový text. Strop zvýšen na 4096 a appka teď loguje, když k oříznutí přece jen dojde.
// 4.14 - 🌍 VLASTNÍ SVĚT — jasnější „nastudování": tlačítko už neneslo zavádějící „(umí i odkaz)" (odkaz jde vložit vždycky, i bez nastudování — text teď zůstal jen v nápovědě popisu). Když Claude při nastudování světa položí doplňující otázku, appka dřív jen NAPSALA „doplňte odpověď do popisu" jako obyčejný text, ale nebylo jasné KAM přesně — teď je celá ta otázka tlačítko: ťuknutí na ni rovnou otevře editor popisu, kam se odpověď píše.
// 4.13 - 🚀 OPRAVEN „5MINUTOVÝ STROP" — reálně vůbec neplatil napříč řetězy: appka sice hlídala globální čas od zadání (viz 4.07), ale tuhle kontrolu měly jen 2 místa v kódu. Hlavní kreslicí smyčky (1. scéna, 4 souběžní kreslíři, ověřovací kola) čekaly jen na SVŮJ VLASTNÍ 240s časovač běhu funkce — a ten se s KAŽDÝM novým řetězem resetuje na nulu. Výsledek: pomalá pohádka (scény po 90–120s) mohla dřít řetěz za řetězem, každý pod svým vlastním limitem, a strop 4:40 od zadání se nikdy neuplatnil — až do pojistky 10 řetězů (≈ 40 minut), přesně jak ukázal screenshot „39:54, 13/15". Teď globální strop hlídají i tyhle smyčky přímo — jakmile uplyne, appka přestane kreslit další scény a rovnou uzavře pohádku s tím, co je hotové (chybějící scény jdou 🖌 opravit ručně).
// 4.12 - 🚨 NALEZENA A OPRAVENA PŘÍČINA 25+ MINUTOVÝCH ZÁSEKŮ („27m?"): appka volala Gemini pro obrázky i vizuální kontrolu přes syrové Node `https.request` BEZ JAKÉHOKOLI TIMEOUTU — když spojení tiše zůstalo viset (žádná odpověď, žádná chyba), promise se nikdy nesplnila ani neselhala, takže se do 📋 deníku nezapsalo vůbec nic a job stál donekonečna (v jednom případě 26 minut mezi dvěma řádky deníku). Obě volání teď mají 90s nečinnostní limit — zaseknuté spojení se přeruší a existující logika opakování/záložního modelu/timeoutu se převezme normálně; ověřeno izolovaným testem (zaseknuté spojení → spolehlivě selže po timeoutu místo věčného čekání).
// 4.11 - 📋 VÍCE DETAILU V LOGU BĚHEM PSANÍ: appka dřív během celého psaní (klidně 2+ minuty) nezapsala do deníku ani řádek — jen tichý heartbeat na pozadí, takže to při delším psaní vypadalo zaseknuté, i když Claude reálně streamoval text. Teď se každých ~20 s zapíše živý postup („✍️ píšu… (1234 znaků zatím, 80s)"), ať je vidět, že se opravdu pracuje.
// 4.10 - 🎙️ 10 NOVÝCH testovacích hlasů z hlasového průzkumu (Gemini TTS, vybráno podle oficiálních popisků stylu — přátelský/živý/veselý/jemný/pohodový/uvolněný/zářivý/vzdušný/svěží/tichý), mluví libovolným jazykem appky; k vyzkoušení v „🎙️ Vypravěč a jazyk pohádky" ve skupině 🌍 Vícejazyčné a vlastní — všech 10 ověřeno živě proti Gemini TTS API
// 4.09 - ▶ ODEBRÁNO brzké čtení: appka dřív nabízela „Číst" ještě za běhu generování (odhadem, že čtenář kreslení nedožene) — na přání appka teď pohádku k přečtení nabídne, až je SKUTEČNĚ celá hotová, nikdy dřív.
// 4.08 - 🩺 TRVALÝ DIAGNOSTICKÝ DENÍK: zrušení (✕) i běžný úklid úložiště dřív smazaly úplně VŠECHNO k jobu — po zastavení zaseknuté přípravy tak nezbyl žádný 📋 deník k diagnostice. Appka teď při každém kroku ukládá kopii deníku do trvalého úložiště (debug-logs/), které úklid nemaže (jen po 30 dnech); appka si navíc pamatuje posledních 15 zrušených/chybových běhů (nová sekce „🩺 Zrušené/chybové běhy" u historie) a jejich celý deník jde znovu otevřít i s odstupem, i po zavření appky
// 4.07 - 🚀 TVRDÝ STROP 5 MINUT na celou přípravu (přes všechny řetězy, ne jen jeden běh funkce): appka teď hlídá globální čas od zadání (4:40, s rezervou na dopsání) a jakmile ho scéna/arch překročí uprostřed opravování, PŘESTANE obrázek dokola překreslovat a přijme první průchod i s drobnou vadou (jde 🖌 opravit ručně) — a jakmile je strop u konce, appka NEZAHÁJÍ další řetěz kvůli obrázkům, radši uzavře pohádku hned s tím, co je hotové, než aby se řetězila donekonečna (viz „Kvarner" — 7 řetězů, 36 minut). Zdravé rychlé pohádky to nijak nezpomalí — strop zasáhne jen tam, kde by se appka jinak zasekla na opravování.
// 4.06 - 🐌 OPRAVA vleklé přípravy (z 📋 deníku: pohádka „Five Stars of Kvarner" běžela 36 minut): 13pravidlová kontrola byla u LEHCE OPÁLENÉ pleti (přímořský/letní příběh) zbytečně přísná — jedno kolo ji vyhodnotilo jako „too dark", jiné jako „too pale" pro STEJNÉ postavy, takže archy padaly skoro do nekonečna; pravidla 3 a 13 teď výslovně POVOLUJÍ přirozenou variaci osvětlení (opálení, teplejší/studenější nasvícení, stín) a hlídají jen SKUTEČNOU změnu etnicity; 🗂️ navíc: když archová fáze jednou dojde k „ani jeden nový panel", příští řetěz (po limitu funkce) už archy ZNOVU nezkouší a jde rovnou sólo cestou — dřív se stejný neúspěšný pokus opakoval na KAŽDÉM restartu funkce zvlášť; ✓ malé oranžové potvrzení přímo u vybraného hlasu ve výběru vypravěče (jasno, který přesně je zvolený, ne jen podle fialového podbarvení řádku)
// 4.05 - ⏱ ČASOMÍRA U PŘIPRAVOVANÉ POHÁDKY: řádek přípravy má novou pilulku „⏱ m:ss" hned za stavem (tiká živě, i mezi jednotlivými polly); 🎞️ živý stav (poslední krok z 📋 deníku) se přesunul na vlastní řádek a delší hlášku, která se nevejde, appka nechá ROLOVAT (stejný trik jako u dlouhého názvu v historii) místo tichého uříznutí — je vidět, co se přesně děje, i když je to dlouhá věta
// 4.04 - 💳 ROZPOZNÁN 3. DRUH vyčerpání Gemini (z chyby „Your project has exceeded its monthly spending cap"): appka dřív znala jen denní kvótu a vyčerpaný kredit — tuhle chybu nepoznala, takže na ni ZBYTEČNĚ PÁLILA DALŠÍ POKUSY (rate-limit odstupňování + záložní model) místo okamžitého zastavení, a job zůstal viset s ošklivou syrovou chybou; nově appka tento MĚSÍČNÍ ROZPOČTOVÝ STROP pozná, hned přestane zkoušet a řekne pravdu — POZOR, je to JINÁ věc než kredit: platba do Google Cloud Billing strop NEZVEDNE, musí se zvednout ručně v AI Studio → Usage and billing → Spend limit (https://aistudio.google.com/)
// 4.03 - 📖 ZKOPÍROVANOU (poslanou/přijatou) pohádku jde upravovat jako BĚŽNOU: appka nezná její postavy z knihovny (heroDescription bylo prázdné) → ✨ Pokračování i 🖌 překreslení dřív neměly ŽÁDNÝ zámek vzhledu ani kontrolu; appka si teď z hotových OBRÁZKŮ + textu jednou zpětně „nastuduje svět" (Gemini vision rekonstruuje popis postav a dějiště) a od té chvíle se s pohádkou pracuje stejně jako s vlastní — ✨ Pokračování navíc nově vždy pošle vypravěči kanonické obsazení a svět MINULÉ pohádky (i vlastní, ne jen zkopírované), ať nepíše charaktery znovu od nuly; ✏️ NOVĚ jde ručně upravit text KAŽDÉ stránky (tužka u titulků) — uložení smaže staré namluvení, ať se přečte nový text
// 4.02 - 🔌 HLAS FUNGUJE OFFLINE: namluvení se dřív vyrábělo LÍNĚ až při čtení — pohádka otevřená bez signálu (tablet v autě, letadlo) tak neměla žádný zvuk, i když si ji uživatel stáhl dopředu; appka teď namluví VŠECHNY stránky hned po dokončení generování, dokud je internet (běží na pozadí, nic neblokuje) — jednou stažená pohádka pak přehraje hlas i úplně offline; 📐 OPRAVA titulkového pruhu na tabletu ve fullscreenu: pruh se přeměřoval jen při změně orientace, ale vstup do fullscreen/změna velikosti okna umí zobrazenou šířku obrázku změnit i beze změny orientace — pruh teď reaguje i na resize a fullscreenchange (čtečka i přehrávač poslané pohádky)
// 4.01 - ⌨️ OVLÁDÁNÍ KLÁVESNICÍ: čtečka i přehrávač poslané pohádky reagují na systémové klávesy — ←/→ (i PageUp/PageDown z prezentérů) listují, MEZERNÍK přehraje/pozastaví vyprávění, Esc mimo fullscreen vede Domů; 🎧 MEDIA SESSION: hardwarové mediální klávesy (▶⏸⏮⏭ na klávesnici, sluchátkách i zamčené obrazovce telefonu) ovládají vyprávění a listování a systém ukazuje název pohádky se stránkou jako u přehrávače hudby
// 4.00 - ⏱ Čas přípravy u POSLANÉ pohádky: pohádka uložená do historie z odkazu neměla odznak ⏱ (délka přípravy se do sdílených dat neposílala) — publikace nově nese prepSec/writeSec i PŮVODNÍ datum vytvoření a příjemce je vidí v historii jako u vlastních pohádek
// 3.99 - 📤 Přehrávač poslané pohádky dotažen: titulkový pruh drží ŠÍŘKU OBRÁZKU (ne celé karty), nové tlačítko 🏠 DOMŮ vede do hlavního menu a zaslaná pohádka se ukládá do HISTORIE appky (text + offline cache obrázků a hlasu) — příjemce ji pak najde v menu jako každou jinou pohádku
// 3.98 - 🕵️ AGENT IDENTITY POSTAV (na „Bella je zase černoška, Valentýna jednou malá jednou velká"): vizuální kontrola dosud NEVIDĚLA referenční portréty — soudila jen podle textu; nově dostává s každou kontrolou kanonické portréty + kotvu příběhu a NOVÉ PRAVIDLO 13 porovnává KAŽDOU postavu s její referencí (stejná tvář, BARVA PLETI, věk a velikost těla, účes, oblečení) — živě ověřeno: cizí tvář verdikt správně zamítá; pravidlo 3 nově hlídá i barvu pleti; 📖 GRADUJÍCÍ DĚJ podle řemesla (rešerše struktury dětských příběhů): kauzální řetěz „PROTO/ALE" (nikdy „a pak"), pravidlo tří s rostoucími sázkami, sázky jen rostou, žádný deus ex machina (vyvrcholení řeší hrdina dřív zavedenými prostředky), po vyvrcholení uspávací zklidnění; story bible má nový bod (5) PRAVIDLA SVĚTA (kánon se nesmí porušit); 🌙 dobrá noc v titulcích jmenuje VŠECHNY zaškrtnuté postavy (i vlastní), které v ději opravdu vystupují (hledání přes kmen jména zvládá skloňování); 📤 přehrávač poslané pohádky vypadá jako čtečka: bílý titulkový pruh s rolujícím textem (synchronně s hlasem), standardní sklo tlačítek, vycentrované šipky
// 3.97 - 📤 OPRAVA POSLANÉ POHÁDKY: stránka /s/ dědila TMAVOU barvu textu z body (appka si ji přebíjí v kontejneru, přehrávač pro příjemce ne) — text i šipky byly na tmavé kartě neviditelné; nově má karta výslovně světlé písmo a tlačítka plné barvy; ⛶ CELÁ OBRAZOVKA: zapne se SAMA při ▶ přehrání i při otočení na šířku (a jde i ručně tlačítkem ⛶) — karta vyplní displej a NEPŘETÉKÁ (na šířku se skryje titulek, obrázek dostane maximum, text roluje pod ním); posílání má už jen JEDNU variantu — 📤 Poslat odkazem (💾 soubor odebrán, mátl dvěma tlačítky); tlačítka v historii (Pokračování/Poslat) jsou VĚTŠÍ a HRANATÁ, ať vypadají jako tlačítka
// 3.96 - 📺 OPRAVA FULLSCREEN ČTEČKY (na šířku): obal obrázku z v3.78 (kvůli 🖌 tlačítku) vypadl z flex rozvržení karty — obrázek přetekl PŘES CELÝ displej a titulkový pruh s textem i ovládání skončily POD obrazovkou (text „neroloval", protože nebyl vidět); obal nově hraje ve sloupci karty roli obrázku (16:9 rám, na šířku výška podle místa) a obrázek ho jen vyplňuje; 🔇 KONEC TICHÉHO SELHÁNÍ HLASU: když se namluvení stránky nepovede (vyčerpaný kredit, výpadek TTS), čtečka místo věčného ⏳ ukáže hlášku se SKUTEČNOU chybou a tlačítkem „Zkusit znovu"
// 3.95 - ✍️ OPRAVA navazování dlouhého psaní (z 📋: „Anthropic 400: This model does not support assistant message prefill"): modely Claude 5 nepodporují prefill, na kterém stálo pokračování psaní po 5min limitu — 15stránkové pohádky proto padaly na 2. pokusu; nově se pokračuje instrukcí v user zprávě (rozepsaný text v <already_written>) a slepení ořezává překryv (až 400 znaků) i případné zopakování celého dokumentu
// 3.94 - 👧 OPRAVA „Bella se proměnila": portréty do kartotéky se kreslily BEZ kontroly (jediná cesta bez QA) — vadný portrét se stal referencí a chyba se replikovala do všech pohádek; nově každý portrét projde jedenácterem (zamítnutí → 1 oprava s výtkami → jinak se použijí fotky), popisy VŠECH postav nově zamykají i BARVU PLETI (fair light skin) a KNIHOVNA SE CELÁ PŘEKRESLÍ (verze portrétů 3 — obnoví se líně při prvním použití postavy)
// 3.93 - 📖 STORY BIBLE — vypravěč povinně „nastuduje svět" PŘED psaním (pole worldNotes): (1) ZÁMEK PROSTŘEDÍ (zápas se hraje NA hřišti s lajnami a brankami, řeka smí být jen ZA ním), (2) reálná správnost (dva týmy v RŮZNÝCH dresech, rozhodčí, soupeři na hřišti), (3) skuteční lidé jsou LIDÉ s plným lidským záznamem (Messi je člověk, ne lev), (4) dokumentární střídání záběrů; bible se připojuje k zámku vzhledu → platí v KAŽDÉM obrázku, archu, ranném kreslení i v kontrole (nové pravidlo 12: dějiště musí odpovídat zámku prostředí)
// 3.92 - ⚽ SKUPINY V POZADÍ povolené (z 📋 deníku: fotbalová pohádka padala na „two identical Kicker characters" a arch prošel 1/9 — týmové scény přirozeně potřebují spoluhráče): psaní smí výslovně přidat skupinu v pozadí („other players of both teams in the background"), kreslení ji maluje jako malé vzdálené postavy nepodobné hrdinům a kontrola ji NEpočítá do přesného počtu (hlásí ji jako group:…); 2. vlna archů se kreslí S KOREKCÍ z výtek 1. vlny (dřív stejný prompt naslepo znovu); UI: menší OK v dialozích, VĚTŠÍ tlačítko 📋 deníku u jobu
// 3.91 - 🟠 JEDNOTNÁ BARVA POTVRZENÍ: všechna potvrzovací tlačítka napříč appkou jsou ORANŽOVÁ („✓ Hotovo" v panelech, OK v dialozích, ✓ OK ve velkých editorech, Uložit svět/postavu…) a rušení je nově neutrální tmavé sklo — dřív byl oranžový naopak Zrušit a pletlo se, co je souhlas
// 3.90 - 🙈 Odebírání hlasů: KAŽDÝ vestavěný hlas (vč. testovacích a filmových prototypů) jde × odebrat z výběru — skryje se na tomto zařízení a tlačítko „↺ Obnovit odebrané hlasy (N)" ho kdykoli vrátí; skrytý hlas se nepoužije ani v automatice; klony a vymyšlené hlasy dál × mažou doopravdy (i u ElevenLabs)
// 3.89 - ✓ POTVRZENÍ ve výběrových panelech: Svět, Postavy, Vypravěč i Pozadí mají dole velké tlačítko „✓ Hotovo" — křížek nahoře jen zavírá a mátl (ruším/potvrzuji?); 🪄 sekce „Vymyslet hlas podle popisu" dočasně schovaná (na přání — kód zůstává, vymyšlené hlasy dál fungují a jdou mazat ×); 🌊 dva NOVÉ hlasové prototypy „dobrodružný animák" (Vaiana vibe): Dobrodružný vypravěč (Fenrir — energický) a Dobrodružná vypravěčka (Leda — mladá, dynamická) s hravou dobrodružnou režií přednesu
// 3.88 - 🎙️ Hlasy dotažené: názvy hlasů se řídí jazykem prostředí (nameEn — v EN už žádný „Gemini vypravěč"); KOMPLETNÍ Gemini matice — pár žena/muž pro VŠECHNY jazyky včetně 🇨🇿 češtiny a 🇬🇧 angličtiny (Sulafat + Iapetus s režií v daném jazyce, nahrazují staré „any" Charon/Aoede); 🎬 dva NOVÉ prototypy „hollywood movie teller": Filmový vypravěč (Algenib — hluboký, gravelly) a Filmová vypravěčka (Gacrux — zralá, dramatická) s trailerovou režií přednesu (cs/en podle textu)
// 3.87 - 🚨 NALEZEN A OPRAVEN KOŘEN NEKONZISTENCE (přísné testy s vizuálním auditem): kontrolní model gemini-2.5-flash „přemýšlel" ~475 tokenů z limitu 500 a verdikt se UTRHL (finish=MAX_TOKENS) — kontrola tak často TIŠE NEBĚŽELA a vadné obrázky (duplicity, fotky, ořezy) procházely neověřené; oprava: thinkingBudget=0 + limit 700 (verdikt za ~2 s, kompletní) + robustní čtení osob z verdiktu; nové pravidlo: klíčový objekt smí být v obraze JEN JEDNOU (test odhalil scénu se DVĚMA majáky); změřený výsledek s funkční kontrolou: 9 scén za ~64 s, arch prošel 7/8 napoprvé, zamítnutí s konkrétním důvodem
// 3.86 - ⚡ ARCHY PARALELNĚ (změřeno: 4K arch generuje ~22 s, stejně jako jedna 1K scéna — sériové archy u 15 stránek byly zbytečná minuta navíc): archy jedné vlny (9+5 scén) se kreslí najednou, max 2 vlny, vlna bez nového panelu končí archovou fázi; důvody zamítnutí se vrací per arch (žádný globální stav — archy běží souběžně); benchmark surové rychlosti: 1K scéna se zámkem vzhledu ~22 s, kontrola ~3,3 s — pipeline už přidává jen QA a uploady
// 3.85 - 🔎 Konec pocitu „seká se": řádek připravované pohádky ukazuje ŽIVĚ poslední krok deníku („🗂️ kreslím arch 9 scén…", „🎨 scéna 7 hotová za 32s") — je vidět, že job pracuje, i když se čísla zrovna nehýbou (arch se počítá až po dokreslení celku); ⚡ optimalizace: portréty postav se načítají souběžně s psaním (−3–5 s), panely archu se ukládají paralelně (−2–4 s/arch), sólo dokreslení jede ve 4 workerech místo 3 (−20 % času nejpomalejší fáze)
// 3.84 - 💰 ROZPOČTOVÁ POJISTKA na pohádku: přes všechny běhy smí vzniknout nejvýš ~4 obrázky na stránku (včetně QA překreslení, archů a řetězů — u 15 stránek limit 72) — pak se job zastaví s jasnou chybou místo pálení kreditu; útrata běhu se sčítá do stavu jobu (imgSpent) a hlídá se před scénou, před archem i na konci běhu — smyčka typu „arch dokola" už NIKDY nemůže protéct bez stropu
// 3.83 - 💳 Vyčerpaný KREDIT Gemini se pozná od denní kvóty: hláška nově říká pravdu („dobijte kredit v Google AI Studio — sám se neobnoví") místo zavádějícího „resetuje se v 9:00"; 📋 deník je ČITELNÝ — text dědil tlumenou barvu odstavců (skoro neviditelný), teď má plný kontrast a dlouhé chybové hlášky se lámou
// 3.82 - 🔁 KONEC SMYČKY ARCHŮ (nalezeno z 📋 deníku: „arch hotový, prošlo 0/8 panelů" pořád dokola): arch, který nepřinese ANI JEDEN nový panel, ukončuje archovou fázi a zbytek jde rovnou sólo cestou s vlastní QA; max 3 archy na běh funkce; do deníku se nově píší DŮVODY zamítnutí panelů (p1: two identical boys… | p2: NEOVĚŘEN…) — uvidíme, jestli padají na konzistenci, nebo na nedostupnosti kontroly
// 3.81 - 🔢 KONEC falešného „(2. pokus)": úvodní zápis stavu z /api/job/start (pojistka proti zombie jobům) se počítal jako minulý mrtvý běh a KAŽDÁ pohádka startovala rovnou jako 2. pokus — nově se skutečný běh pozná podle updatedAt; zdravé navázání psaní po 5min limitu funkce se v řádku ukazuje jako „✍️ Píšu… (pokračuji)" místo strašidelného čísla pokusu (pokusy se číslují jen při psaní BEZ pokroku); časovač předání při psaní posunut na 280 s (méně zbytečných řetězů)
// 3.80 - 👋 Konec nesmrtelného „týpka s kávou": kniha na ploše se obnovovala z rozpracovaného stavu BEZ vazby na historii — smazaná pohádka se tak po každém přepnutí okna vracela donekonečna; nově se rozpracovaný stav páruje s historií (nese id), osiřelý stav smazané pohádky se zahodí a na plochu se místo něj načte POSLEDNÍ pohádka z historie (z offline cache); plocha se doplní o poslední pohádku i po čistém startu appky
// 3.79 - 📋 Deník se k hotové pohádce doplní i ZPĚTNĚ: když pohádku dokončila starší verze appky nebo jiné zařízení (odznak ⏱ bez 📋), appka si při startu deník stáhne ze serveru, dokud tam ještě žije (~1 hodina po dokončení)
// 3.78 - 🖌 Překreslit jde KAŽDÝ obrázek: v rohu stránky ve čtečce je štěteček — nový obrázek projde kontrolou a NAHRADÍ starý (uloží se k pohádce, dřív se oprava po reloadu ztratila; oprava starší pohádky navíc používala kontext posledního generování místo té otevřené); kontrola má nové PRAVIDLO STYLU: fotografie/fotorealistický/3D obrázek = okamžité zamítnutí (tudy prošel „týpek s kávou" — vůbec nic nekontrolovalo, jestli je to malovaná ilustrace)
// 3.77 - 🔒 ZPŘÍSNĚNÍ jedenáctera: NEOVĚŘENÝ panel archu (kontrola 3× selhala, typicky rate-limit) se už NEPŘIJÍMÁ — jde na sólo dokreslení s vlastní QA; kontroly panelů běží po 4 (všech 9 naráz umělo vyčerpat limit kontrolního modelu — právě tudy proklouzly duplicitní postavy a předměty); sólo scéna s nedostupnou kontrolou dostane po pauze ještě jeden pokus o ověření; 🎬 titulky bez technologií (know-how) — jen hrdinové pohádky a poděkování; 🌙 dobrou noc na konci jmenovitě VŠEM postavám aktuální pohádky, v jazyce vyprávění (Godnat, Nicolas, Valentina og Jakob…)
// 3.76 - 🗑️ Smazaná pohádka zmizí i z plochy: mazání z historie dřív nechalo knihu načtenou dole na stránce (vypadalo to, že se smazání nepovedlo); 📋 deník přípravy se nově UKLÁDÁ k hotové pohádce — v historii má pohádka odznak „⏱ čas 📋" a ťuknutím se deník otevře i po dokončení (kroky, trvání, chyby)
// 3.75 - 🔧 Drobnosti UI: +/− v počtu stránek přesně vycentrované (flex + optická korekce baseline); tlačítko „🎙️ Nahrát rodinný hlas (klon)" dočasně schované (celý flow zůstává v kódu — vrací se jedním řádkem); existující klony dál fungují a jdou mazat ×
// 3.74 - ✂️ Konec uřezaných zadání: ✨ Rozvinout dřív četlo jen prvních 600 znaků kostry a výstup tvrdě utínalo na ~900 tokenech (osnova končila uprostřed věty — „…vede král") → vstup nově až 3000 znaků, výstup do ~280 slov s instrukcí VŽDY dokončit poslední větu a stropem 2000 tokenů jen jako pojistkou; 🎲 Vymysli námět čte z poznámek 800 znaků místo 300; samotné zadání pohádky se do psaní posílá CELÉ (nikdy se neřezalo)
// 3.73 - 🚩 Přepínač jazyka prostředí: vlajky nově jako vestavěné SVG — emoji vlajky 🇨🇿/🇬🇧 Windows neumí vykreslit a rozpadly se na písmena („cz CZ / GB EN"); teď vypadá přepínač stejně na mobilu i desktopu
// 3.72 - ⚡ ZRYCHLENÍ PŘÍPRAVY (cíl 2–3 min): (1) scéna 1 se kreslí UŽ BĚHEM psaní — jakmile ji stream dopíše, maluje se souběžně se zbytkem příběhu (psaní ~2 min a kotva ~1 min se překryjí, dřív šly za sebou); (2) kontroly panelů archu běží VŠECHNY paralelně (po 3 stály ~3× déle); (3) líná sanitizace promptů — rychlá regexová očista hned, LLM přepis (2–5 s na scénu) až když filtr obsahu skutečně zablokuje; deník 📋 nové kroky ukazuje („⚡ scéna 1 se kreslí souběžně s psaním")
// 3.71 - 📋 DENÍK PŘÍPRAVY: každý job si vede záznam kroků s časy a chybami (start/řetěz funkce, psaní s délkou a znaky, souhrn PDF, každý arch i scéna s trváním, chyby Gemini, kvóta, předání štafety, HOTOVO s celkovým časem) — u připravované pohádky je pod ✕ nové tlačítko 📋, které deník otevře (aktualizuje se živě); posledních 60 událostí jede ve status.json, tak je vidět ze všech zařízení — konečně přesně uvidíme, KDE se čas ztrácí a jaké chyby padají
// 3.70 - ♻️ KONEC SEKANÉ PŘÍPRAVY: příprava pohádky se dřív po 5min limitu Vercel funkce zastavila a čekala, až ji OTEVŘENÁ appka nakopne (zamčený telefon = mrtvý job → „příprava 78 minut"); teď se job před limitem SÁM předá další serverové funkci (psaní naváže na rozepsaný text, kreslení přeskočí hotové scény) — pohádka se dokončí i se zavřenou appkou; „(2. pokus)" u psaní je nově jen zdravé navázání: zaseknutí se pozná podle nulového pokroku rozepsaného textu (3× bez pokroku = stop s chybou), tvrdý strop 8 běhů psaní a 10 řetězů; klientský watchdog zůstává jako záloha
// 3.69 - 🎙️🌐 Vypravěč a jazyk pohádky SLOUČENÉ do jednoho rolleru: sekce „Jazyk pohádky" zmizela — jazyk určuje vybraný vypravěč (hlas s vlajkou 🇨🇿/🇬🇧/🇭🇷/🇩🇰/🇸🇰 píše i vypráví svým jazykem, vícejazyčné hlasy jazykem prostředí); 📷 „Fotky světa" z vlastního světa odstraněny (svět se popisuje textem, starší světy s fotkami dál fungují); ⏱ Spotřeba nově ukazuje čas přípravy POSLEDNÍ pohádky (velké číslo) + průměr a rozsah v popisku
// 3.68 - 👶🧒👦 STRUKTUROVÁNÍ POHÁDKY PODLE VĚKU: čtyři vývojová pásma podle rámců dětské literatury — BATOLE 2–3 (1–3 věty/scéna max 8 slov, kumulativní struktura s refrénem, otázky posluchači, ŽÁDNÝ temný okamžik, usínací rituál na konci), ŠKOLKA 4–5 (2–4 věty, jeden jemný zvrat, napětí jen na jednu scénu, pocity pojmenované jednoduše), MALÝ ŠKOLÁK 6–7 (3–5 vět, plný oblouk s temným okamžikem, nová slova z kontextu, 1 pravdivá zajímavost), VĚTŠÍ ŠKOLÁK 8+ (4–7 vět, zaseté vodítko/falešná stopa, mini-cliffhangery, dilemata s cenou, přesné zajímavosti); nový výběr „Pro jaký věk vyprávět" — Auto (podle postav, jako dřív) nebo ručně 2–3/4–5/6–7/8+ (pásmo 8+ bylo dřív nedosažitelné)
// 3.67 - ▶ Brzké čtení BEZ ČEKÁNÍ: tlačítko „Číst" se ukáže teprve, když appka spočítá, že čtenář generování nedožene — porovnává zásobu čtení (souvislé hotové stránky × tempo předčítání) s odhadem zbývajícího kreslení (měřené tempo scén tohoto jobu) s 20% rezervou; hlas 1.–2. stránky se namluví DOPŘEDU ještě před ukázáním tlačítka (po otevření hraje hned — konec ⏳ na Přehrát) a při čtení se předvyrábí hlas 3 stránek dopředu místo 2
// 3.66 - 🌍 Vypravěči pro VŠECHNY jazyky pohádek: k češtině/angličtině/chorvatštině přibyly 🇩🇰 dánský a 🇸🇰 slovenský pár (žena Sulafat + muž Iapetus, režie přednesu v daném jazyce) — výběr hlasu v automatice rovnou určuje jazyk pohádky; roller hlasů je nově SESKUPENÝ podle jazyků (🇨🇿→🇬🇧→🇭🇷→🇩🇰→🇸🇰→🌍 vícejazyčné a vlastní); ⏱ panel Spotřeba ukazuje průměrné trvání přípravy pohádky (+ nejrychlejší–nejpomalejší) — každý hotový job zapisuje délku přípravy do záznamu spotřeby
// 3.65 - 🇭🇷 Chorvatské Gemini hlasy ve výběru vypravěče: Hrvatska pripovjedačica (žena, Sulafat) a Hrvatski pripovjedač (muž, Iapetus) — režie přednesu se dává chorvatsky (správný přízvuk a výslovnost); výběr chorvatského hlasu v automatice rovnou přepne i jazyk pohádky na chorvatštinu (ruční volba v rolleru Jazyk má dál přednost); ukázka hlasu a „dobrou noc" se u hlasu s pevným jazykem říká jeho jazykem (Laku noć…)
// 3.64 - OPRAVA výběru postav: přidané/odebrané postavy se ukládají PRŮBĚŽNĚ (dřív jen při spuštění generování — po zavření appky se výběr vracel k minulé pohádce; platí i pro vlastní postavy, svět a počet stránek) a respektuje se i záměrně prázdný výběr; 🌐 nový roller „Jazyk pohádky": Automaticky / 🇨🇿 Čeština / 🇬🇧 Angličtina + testovací jazyky 🇭🇷 Chorvatština, 🇩🇰 Dánština, 🇸🇰 Slovenština (pohádka se jimi napíše i namluví — vypravěč je vícejazyčný; testovací jazyk jde odebrat × a tlačítkem ↺ zase obnovit)
// 3.63 - 🧹 Šestice UX oprav: (1) VŠECHNY pohádky v jednom rolleru se skupinami (Světy → České a klasické → Andersen, abecedně) a pod ním 📍 „Pohádka podle mé lokality" (samostatná GPS sekce zmizela); (2) mazání hlasů hlásí chybu místo tichého selhání a seznam se vždy srovná se serverem; (3) ✕ pro smazání textu je NAD polem vpravo — už nezakrývá text; (4) návrhy textů i ukázky hlasů se řídí jazykem prostředí (Voice Design mluví česky v CZ, anglicky v EN); (5) ukázky hlasů přes jeden přehrávač: ⏳ načítám, ⏹ zastaví ťuknutím, nikdy se nepřekrývají, panel se výběrem nezavírá (pohodlné porovnávání) + po uložení hlasu potvrzení; (6) tlačítko „Nahrát rodinný hlas" je vidět vždy — při 4 klonech poradí smazat a nahrát lepší nahrávku
// 3.62 - VELKÁ OPRAVA konzistence při mnoha postavách (analýza „Glowing Shell": Janova polokošile na cizím chlapci, dva fialové hoodie, tmavovlasá „Eva", zvíře navíc): příčinou bylo 9 postav v každé scéně — (1) psaní nově smí do scény jmenovat max 4 postavy (finále 6), velké obsazení se střídá po skupinkách a zákaz „everyone/the family" v promptech; (2) kreslení dostává JEN portréty postav jmenovaných v dané scéně/archu (ne všech 9 najednou — to míchalo identity); (3) kontrola vyžaduje PŘESNÝ počet lidí = počet jmenovaných a padá na duplicitní podpisové oblečení i dospělé oblečení na dítěti
// 3.61 - 🧪 Dva testovací hlasy Google Gemini ve výběru vypravěče (muž Charon + žena Aoede, mluví česky i anglicky, ~poloviční cena) pro porovnání kvality s ElevenLabs; ⏱ tracker délky přípravy: každá pohádka si měří čas psaní a celkovou dobu do hotova — v historii je odznak ⏱ m:ss (podržením detail psaní)
// 3.60 - ▶ ČTENÍ HNED PO PRVNÍ SCÉNĚ: na běžící pohádce se objeví zelené tlačítko „Číst" jakmile je nakreslená první stránka (~1,5 min od zadání) — čtete, zatímco se zbytek dokresluje na pozadí a stránky přitékají do čtečky průběžně (na nedokreslenou stránku se nedá přeskočit, sama se otevře, jakmile je hotová); OPRAVA jazyka: pohádka s klonem/vymyšleným hlasem (mluví oběma jazyky) se píše v jazyce prostředí — v EN prostředí anglicky (dřív padala na češtinu)
// 3.59 - 👨‍👧‍👦 Až 4 pojmenované rodinné klony hlasu (Tatínek, Nicolásek, Babička…): před nahráváním se hlas pojmenuje, každý je v rolleru zvlášť a maže se × po jednom; „vylepšení" = smazat a nahrát delší/čistší nahrávku; dětské hlasy fungují (instant klon bývá u dětí kolísavější — pomáhá klidné čtení po částech)
// 3.58 - 🪄 Hlas podle popisu (Voice Design): v sekci Hlas napíšete, jak má vypravěč znít („vřelá babička, pomalé tempo…"), appka vygeneruje 3 ukázky, vyberete → hlas se uloží do výběru (max 8, mazání × přímo v rolleru — platí i pro klon); ladění přednesu bez nasazování přes env ELEVEN_STABILITY/STYLE/SIMILARITY/SPEED
// 3.57 - 🎙️ Rodičovský hlas a výběr vypravěče: nová sekce Hlas vypravěče — výchozí automatika (podle jazyka), roller hlasů s okamžitou ukázkou po výběru, a KLONOVÁNÍ hlasu rodiče: přečtete ~minutový text (připravený, s intonacemi pohádky), appka vytvoří klon u ElevenLabs (Instant Voice Cloning, tarif Starter+), přehraje ověřovací ukázku a klon pak vypráví pohádky česky i anglicky; vylepšení = nahrát znovu, smazání jedním ťuknutím (vč. nahrávky u ElevenLabs — appka ji neukládá)
// 3.56 - Ošetření cizích postav a prohazování identit (Jan↔Jakob, Jana↔Eva): (1) zámek vzhledu nově výslovně zakazuje slučování/záměnu podobných postav a použití portrétu na jinou postavu; (2) arch má PANEL CAST RULE — v panelu smí být jen postavy jmenované v JEHO popisu, i když jsou portréty ostatních přiložené; (3) kontrola musí každou viditelnou osobu VYJMENOVAT a přiřadit k postavě — nepřiřazená osoba (UNKNOWN) = zamítnutí, stejně jako míchané rysy dvou postav; pojistka v kódu zamítne i verdikt „ok" s nepřiřazenou osobou
// 3.55 - 📍 Před systémovým dotazem na polohu se ukáže vlastní okno v designu appky (vysvětlí, že poloha slouží jen na jeden návrh a neukládá se; systémové okno prohlížeč stylovat nedovolí — bezpečnostní pravidlo webu); zamítnutá poloha dá srozumitelnou hlášku
// 3.54 - Upozornění na mobilní data přepočítáno: výroba pohádky dnes stáhne ~5 MB (WebP scény), ne 30 MB z dob PNG; namluvení se stahuje až při přehrávání (~300 kB na stránku)
// 3.53 - 💰 Přesné účtování obrázků: počítají se SKUTEČNÁ generování (včetně QA překreslení a portrétů), 1K obrázky a 4K archy zvlášť (arch $0,151 nese až 9 scén) — cena v panelu Spotřeba nově odpovídá realitě; počet pohádek se počítá jen ze záznamů celých pohádek (líné namluvení/dokreslení stránky už falešně nepřičítá pohádku)
// 3.52 - 👫 Konec trojité Evy a Jakoba: postavy ve výběru ukazují FOTKY a duplicitní vlastní postavy (stejné jméno jako vestavěná, i spojená „Eva & Jakob") se automaticky uklidí — výběr přejde na vestavěné (kanonický popis + portrét, fungují všude); 💡 Ponaučení nahrazeno 📍 „Pohádka z místa, kde jste": appka zjistí polohu (nikam se neukládá), pozná místo a navrhne námět z okolí; OPRAVA zaseknutí na poslední scéně: arch se nekreslí opakovaně kvůli QA (nevešlo se do 5min limitu) — vadné panely jdou rovnou sólo dokreslení
// 3.51 - 🗂️ Archy scén: obrázky se kreslí po skupinách v jednom 4K obrázku (mřížka 3×3, až 9 scén za cenu jednoho = 0,39 Kč/scénu místo 1,56 Kč) a rozřezávají se podle bílých linek; z desatera je JEDENÁCTERO — nové pravidlo: nic důležitého oříznutého okrajem (hlavy, lodě, stavby, měsíc) a nikdo jmenovaný nesmí chybět (kontrola nově dostává i popis scény); každý výřez se kontroluje zvlášť, vadný arch se až 2× překreslí a neprošlé panely se dokreslí sólo; vypnutí přes IMAGE_SHEET_MODE=off
// 3.50 - 🔀 Líný druhý konec: obrázky větve B se malují AŽ když čtenář na rozcestí druhý konec opravdu vybere (progres okno „Kreslím druhý konec…"), první výběr chvilku počká, pak je konec uložený — úspora ~1/3 obrázků u pohádek s alternativními konci; sdílení a export si oba konce dokreslí automaticky; 💰 prompt caching u psaní příběhu (neměnný systémový prompt se platí ~1/10) a účtování obrázků kreslených mimo frontu
// 3.49 - 🎙️ Hlas se vyrábí AŽ PŘI ČTENÍ hotové pohádky (úspora ~20–40 % nákladů na hlas): generování dělá jen text a obrázky, namluvení vzniká pro čtenou stránku + 2 další dopředu a ukládá se (platí se jen jednou); před sdílením odkazem a exportem do souboru se chybějící namluvení automaticky doplní, takže odeslaná pohádka je vždy kompletní; spotřeba hlasu se účtuje při namluvení
// 3.48 - Kartotéka v2 podle zpětné vazby: Valentýnka sahá Nicolasovi po ramena (ne do půli), James je PŘESNĚ stejně vysoký jako Nicolas, táta Jan má víc vlasů (plnější nahoře, kouty jen na spáncích — podle nové fotky) a zamčené bílé tenisky; portréty se překreslí (verze v2) a stejné výšky se učí i psaní příběhu
// 3.47 - 🎨 Portrétová kartotéka: každá vestavěná postava se JEDNOU namaluje v pohádkovém stylu (celá postava podle fotek a kanonického popisu) a kreslení scén dostává tento hotový portrét místo fotky — stejná podoba a velikost postav v každé pohádce (konec „jednou vyšší, jednou menší“) a méně opravných překreslení = levnější pohádky; náhled kartotéky na /api/portraits (?redraw=<id> namaluje postavu znovu)
// 3.46 - 👫 Eva a Jakob jsou vestavěné postavy s fotkami (na všech zařízeních, s kanonickým popisem vzhledu — konzistence jako u rodiny); 🇩🇰 Andersenovy dánské pohádky ve výběru světů (Malá mořská víla, Malenka, Cínový vojáček, Divoké labutě, Slavík, Létající kufr + stávající 4) — válec je rozdělený na skupiny 🇨🇿 České a klasické / 🇩🇰 Andersen; válec vylepšen: krajní položky jdou dorolovat do středu a jsou čitelné (větší odsazení, jemnější náklon a mlžení)
// 3.45 - OPRAVA věčného „Píšu… (2. pokus)": dlouhá pohádka (alternativní konce, hodně stránek) se nevešla do 5min limitu serverové funkce a po restartu se psala znovu OD NULY — pořád dokola; teď se rozepsaný text každých 20 s ukládá a po restartu psaní NAVÁŽE přesně tam, kde skončilo (Claude pokračuje v rozepsané odpovědi), takže se každá pohádka vždy dopíše
// 3.44 - OPRAVA konzistence „všude a pořád": kontrola desatera běží na serveru (platí pro všechna zařízení), ale měla tři díry — (1) když samotná kontrola selhala (přetížení), obrázek prošel BEZ prohlídky → teď se kontrola opakuje až 3×; (2) utržená odpověď kontroly prošla jako „ok" → teď JSON režim s velkým limitem; (3) po neúspěšných opravách se posílal vadný obrázek → teď 2 korekce + 1 čerstvé překreslení a drží se NEJLEPŠÍ ověřený pokus; kontrolu dělá silnější model (gemini-2.5-flash) a kartotéka postav se jí předává celá (8 000 znaků místo 4 000)
// 3.43 - 🧒 Postavy jako rolovací válec (jako světy): tlačítko „Vybrat postavy" ukazuje vybraná jména, uvnitř válce se postavy zaškrtávají oranžovými ✓ (vícero najednou, vlastní postavy s fotkou a ×); „+ Vlastní postava" zůstává tlačítkem pod válcem; pole se zadáním pohádky je výrazně větší (významná součást formuláře)
// 3.42 - Velký editor sedí u horního okraje displeje (pod ním zůstává místo na klávesnici) a tlačítka ✨ Rozvinout / ✕ Zrušit jsou prohozená (Rozvinout vlevo)
// 3.41 - Popis vlastního světa se píše ve stejném velkém editoru přes celý displej jako zadání pohádky (ťuknutí do pole ho otevře, ✕ Zrušit vrátí původní text); obě hlavní pole na vyplnění (zadání pohádky, popis světa) mají tenkou oranžovou linku; psané pole se zvedá VÝŠE nad klávesnici (do horní pětiny obrazovky, s větší rezervou)
// 3.40 - Zjednodušení: hlas vypravěče se vybírá AUTOMATICKY podle jazyka prostředí CZ/EN (tlačítka hlasu zmizela); tlačítko Přeložit odstraněno — pohádka se píše v jazyce prostředí bez ohledu na jazyk zadání (appka si to přebere sama); podtitul bez zmínky o tatínkově hlasu; 🎬 úvodní obrazovka při otevření appky: pokaždé jiný pohádkový motiv (vesmír, džungle, moře…), nadpis, verze a slogan „Svět pohádek podle vašich přání" — sama zmizí, ťuknutím se přeskočí
// 3.39 - Pod přepínačem 🌐 CZ|EN je malý popisek „přeložit text pohádky", aby bylo na první pohled jasné, co přepínač dělá (ve formuláři i ve velkém editoru)
// 3.38 - 🌐 Přeložit je skutečný přepínač s jezdcem (jako CZ/EN nahoře): oranžový jezdec stojí na jazyku, kterým je text napsaný, ťuknutím přejede na druhou stranu a text se přeloží — ve formuláři i ve velkém editoru
// 3.37 - 💰 Spotřeba přehledněji: čtyři karty se statistikami — 📚 počet pohádek, 📱 kolik zařízení tvořilo, 🎨 obrázky s cenou v Kč, 🎙️ namluvené znaky; každé zařízení dostává anonymní ID, takže po nasdílení uvidíte, kolik lidí appku používá (počítá se u nově vytvořených pohádek)
// 3.36 - 🔟 Desatero konzistence (DESATERO-KONZISTENCE.md): vizuální kontrola projíždí 10 pravidel — počet lidí, každý právě jednou, vlasy postavu po postavě, oblečení na správné postavě, jednotné oblečení scény, proporce, anatomie, klíčové předměty, žádný text — a vadný obrázek se překreslí až 2×; 🔀 návrat k rozbočce: tlačítko „Druhý konec" ve čtečce (i ve sdíleném odkazu a offline souboru) vrátí pohádku k výběru; Přeložit správně pozná anglický text s českými jmény (skutečný toggle)
// 3.35 - 🌐 Přeložit funguje jako toggle do opačného jazyka, než kterým je text napsaný (česky → EN, anglicky → CZ) — tlačítko ukazuje směr („Přeložit → EN")
// 3.34 - 🌐 Přeložit místo Smazat text: zadání se přeloží do jazyka vybraného vypravěče (pro anglickou pohádku do angličtiny, jména zůstávají) — ve formuláři i ve velkém editoru; mazání textu má nově oranžový ✕ přímo v rohu textového pole
// 3.33 - OPRAVA zasekávání psaní s vloženým PDF: velký dokument se při psaní četl celý a pohádka se nevešla do časového limitu („Píšu… (3. pokus)") — PDF se teď JEDNOU shrne do podkladu (místa, jména, data, program), který se uloží k pohádce; psaní pak běží rychle a případný restart už PDF znovu nečte
// 3.32 - OPRAVA rozhozeného formuláře po vložení PDF: dlouhý název souboru roztahoval kartu (a s ní celou stránku do šířky) — název se teď zkracuje trojtečkou a karta drží šířku formuláře
// 3.31 - Appka se při psaní už nezvětšuje/nezmenšuje: klávesnice stránku jen překryje (nemění její velikost) — viditelnost psaného pole dál zajišťuje automatický posun nad klávesnici
// 3.30 - OPRAVA přiblížené appky: fokus pole s malým písmem spouštěl auto-zoom celé stránky, který se nevracel (proto „ujíždění" editoru i posunutý jazykový přepínač) — všechna pole mají min. 16px písmo a viewport zoom zakazuje; velký editor navíc zamyká stránku pod sebou a je vyjmutý z posunu pod klávesnicí
// 3.29 - ✨ Rozvinout vychází i z vloženého PDF (hlavní zdroj: konkrétní místa, jména, data a program z dokumentu) a z aktuálně vybraného světa — respektuje přepínač použití PDF; tlačítka editoru zpět na plnou velikost (64 px, stejná); jazykový toggle vpravo nahoře s oranžovým jezdcem
// 3.28 - Tlačítka ve velkém editoru přání jsou přesně stejně velká (pevná výška 54 px, text na jeden řádek)
// 3.27 - Odstraněno dvojité Zrušit u přidávání postavy/světa: chip nahoře zůstává „+ Vlastní postava/svět" (jen se zvýrazní), rušení má jen jedno oranžové tlačítko v panelu
// 3.26 - Vlastní postava může mít až 5 fotek (lepší podoba tváře na obrázcích — fotky jdou do psaní i kreslení); velký editor přání: 4 stejně velká tlačítka v mřížce (✕ Zrušit, 🧹 Smazat, ✨ Rozvinout, ✓ OK); přepínač jazyků CZ/EN jako velký toggle s jezdcem
// 3.25 - Vložené PDF jako hezká karta: světlý název, popisek stavu, přepínač „použít v pohádce" (PDF zůstane nahrané, jen se dočasně vypne) a oranžové ✕ pro odebrání
// 3.24 - Velký editor přání má oranžové ✕ Zrušit — zavře okno a vrátí text do podoby před otevřením (OK změny nechá, 🧹 maže)
// 3.23 - Jednotné tlačítko Zrušit napříč aplikací: oranžové s křížkem (✕ Zrušit) — v potvrzovacích oknech, u přidávání postavy/světa i u okna s odkazem na poslanou pohádku
// 3.22 - PDF inspirace až 10 MB (větší soubory jdou rovnou do úložiště — dřív končily na limitu 3,5 MB, tlačítko ukazuje ⏳ při nahrávání); systémové hlášky (alert) nahrazeny stylovým oknem appky s tlačítkem OK
// 3.21 - Oblečení podle počasí KONKRÉTNÍ SCÉNY: šatník má venkovní a vnitřní variantu (venku bundy, uvnitř sundané) a všechny postavy v jedné scéně jsou oblečené stejně — nikdo nabalený vedle někoho v tričku (hlídá i vizuální kontrola); nadpis výběru pokračování je bílý (byl tmavý); výběr konce se už neukazuje mimo čtečku (plaval nad formulářem)
// 3.20 - Náhled pozadí předělán: žádná oka — PODRŽENÍM světa se ukáže malá karta s ilustrací, která se plynule roztáhne na celý displej; puštěním se náhled zavře, ťuknutím svět vyberete (nápověda přímo v nabídce)
// 3.19 - Výběr pozadí: náhled 👁 je u KAŽDÉHO světa (ťuknutí vybere pozadí a ukáže ho přes celý displej) a nabídka má záhlaví s oranžovým ✕ — křížek pro odchod mají teď všechny rolovací nabídky
// 3.18 - Oranžový vycentrovaný křížek ✕ u všech rozbalených panelů; výběr světa je sbalený za tlačítkem „Vybrat svět" a má stejný ✕; v nabídce pozadí nová položka 👁 Ukázat celé pozadí — schová všechna tlačítka, ťuknutí kamkoli vrátí zpět; velký editor přání: světlejší podklad a vynucený bílý text
// 3.17 - Text ve velkém editoru přání je bílý (byl příliš tmavý na tmavém pozadí), světlejší i kurzor a nápověda
// 3.16 - Přejmenováno na „Alternativní konce"; popisek přepínače zůstává bílý i po zapnutí; rozbalené rollery (ponaučení, klasické pohádky) mají křížek ✕ — jdou zavřít i bez výběru
// 3.15 - Svět pohádky jako 3D roller (vestavěné světy; vlastní světy a Vlastní svět zůstávají tlačítka, první položka „Bez světa"); Dva konce jako klasický přepínač zleva doprava; Přání & inspirace se po ťuknutí otevře ve velkém okně přes displej — celý text viditelný, mazání i OK po ruce
// 3.14 - Rozepsané zadání pohádky se neztratí: text v poli Přání se průběžně ukládá do telefonu a přežije aktualizaci appky i přepnutí do jiné aplikace; smaže se tlačítkem 🧹
// 3.13 - Dva konce a Vybrat ponaučení jsou tlačítka přes celou šířku (jako Hudba); rolovací seznamy (ponaučení, klasické pohádky) mají 3D roller efekt — položky se při rolování naklápí jako na válci
// 3.12 - Logika počasí: postavy se v zimě/na horách obléknou (bunda, čepice, šála, sněhule), v horku odlehčí (kraťasy, sandály, plavky), v dešti pláštěnky — vždy přes zamčený Story outfits (stejný převlek ve všech scénách, bundy nemizí), postavy zůstávají rozpoznatelné podle svých barev; vizuální kontrola hlídá, že převlek na obrázku opravdu je
// 3.11 - 🪄 Rozvinout: nové tlačítko u pole přání — z pár slov („legendy z historie Benátek…") AI rozepíše detailní osnovu (pojmenované postavy, místa, letopočty, kostýmy, zápletka), kterou si před generováním můžete upravit; větší tlačítko ▶ u uložených pohádek (58 px — pohodlně se trefí)
// 3.10 - Diagnostika přímo v appce: když se psaní opakuje, řádek pohádky ukazuje číslo pokusu („✍️ Píšu… (2. pokus)") a žlutě POSLEDNÍ CHYBU, kvůli které předchozí pokus spadl — konec hádání, co se děje
// 3.09 - Konec maskovaných chyb při psaní: restart jobu dřív smazal chybovou hlášku (věčné „Píšu…") — teď se chyba přenáší dál a po 3. neúspěšném pokusu se pohádka zastaví s viditelnou příčinou; nová diagnostika /api/job/list ukáže stav a chyby všech jobů
// 3.08 - OPRAVA zasekávání ve fázi „Píšu…": dlouhý scénář (hlavně dva konce ≈ 16+ scén) se nestreamovaný nevešel do 250s limitu jednoho pokusu — psaní teď STREAMUJE (text přitéká průběžně, žádný útes) a job posílá heartbeat i během psaní, takže se neukazuje falešné ⚠ zaseknutí
// 3.07 - Výběr konce předělán na dvě velké grafické karty: obrázek první scény každé cesty + popisek (jasně vidět, kam která vede) — v appce, ve sdíleném odkazu i v offline souboru; OPRAVA: Claude vrací konce v novém jednoznačném formátu (endingA/endingB) — dřív se větev občas zahodila a tlačítka se vůbec neukázala (otázka zůstala jen v textu)
// 3.06 - Dva konce vylepšeny: rozdvojení přichází v ~2/3 příběhu (ne až před poslední stránkou) a každý konec má aspoň 2–4 plnohodnotné scény; poslední společná scéna KONČÍ hlasovou otázkou se jmenováním obou cest a pohádka se zastaví, dokud dítě nevybere (tlačítka se ukážou po dovyprávění otázky); oprava: výběr konce se neztratil při otevření hotové pohádky z řádku jobu ani při doplnění chybějících obrázků
// 3.05 - 🔀 Pohádka se dvěma konci: přepínač „Dva konce (na výběr)" ve formuláři (defaultně vypnuto, před generováním se potvrzuje) — vypravěč na konci společného děje položí otázku a čtenář vybere ze dvou tlačítek, jak pohádka skončí; oba konce se předgenerují (obrázky i hlas), takže druhý večer jde vybrat ta druhá cesta; funguje ve čtečce, ve sdíleném odkazu i v offline souboru
// 3.04 - Offline soubor s pohádkou předělán na čtečku jako v appce: obrázek přes celý displej, text v čitelném pruhu dole (bílá na tmavé), velká viditelná tlačítka ← ▶ →; na šířku se schová titulek, ať má obrázek maximum místa; větší tlačítka u uložených pohádek (Pokračování/Poslat/Soubor + koš) — na tabletu se lépe trefují
// 3.03 - 💾 Pohádka jako soubor: u uložené pohádky tlačítko Soubor — zabalí obrázky, text i namluvení do jednoho HTML souboru s přehrávačem; pošlete ho Quick Share/Bluetooth BEZ internetu a příjemci se přehraje offline (bez platnosti 90 dní)
// 3.02 - Pohádky jsou ~5× menší: nové obrázky se ukládají jako WebP místo PNG (15 stránek ≈ 5–8 MB místo 25+ MB — méně místa v telefonu, rychlejší stažení i poslání); starší uložené pohádky zmenší telefon automaticky při posílání
// 3.01 - OPRAVA posílání pohádky: obrázky se nahrávají rovnou z prohlížeče do úložiště (binárně) — velké scény přes server narážely na limit 4,5 MB na request a nahrávání se točilo dokola; po chybě naváže další pokus tam, kde skončil (nenahrává od začátku); 2 pokusy na soubor a případná chyba se ukáže i s důvodem
// 3.00 - Poslat pohádku v2: nahrávání ukazuje průběh (⏳ 3/15), jede 3 scény najednou (rychlejší) a po dokončení se otevře okno s odkazem a tlačítky Sdílet… / Kopírovat — sdílecí nabídka Androidu se dřív po dlouhém nahrávání nesměla otevřít (vyžaduje čerstvé ťuknutí), proto to vypadalo, že se nic nestalo
// 2.99 - 📤 Poslat pohádku: u uložené pohádky tlačítko Poslat — nahraje obrázky i namluvení a pošle odkaz (WhatsApp, e-mail…) na přehrávací stránku, příjemce nic neinstaluje (odkaz platí 90 dní); OPRAVA konzistence vymyšlených postav: úprava promptu měla nízký strop a ořezávala popisy postav na konci (jednou blond, podruhé hnědé) — zvednuto + pojistka, vizuální kontrola čte celou kartotéku a hlídá barvu vlasů postavu po postavě, vymyšlení lidé musí mít popis stejně přísný jako hrdinové
// 2.98 - 💡 Ponaučení pohádky: rolovací výběr 13 ponaučení (pomáhat druhým, nevzdávat se, mluvit pravdu…) — vplete se přirozeně do děje, bez kázání; 📖 Pokračování: u každé uložené pohádky tlačítko ✨ Pokračování — nový díl naváže na minulý děj, hrdinové si pamatují, co zažili (obnoví se i obsazení a svět); 🎲 námět obojí respektuje
// 2.97 - Klávesnice na tabletu podruhé: appka si sama změří výšku klávesnice (visualViewport) a psané pole posune NAD ni — funguje i v prohlížečích, které klávesnicí obsah překrývají (Samsung Internet, WebView)
// 2.96 - Oprava psaní na tabletu: otevřená klávesnice stránku zmenší místo překrytí (interactive-widget) a pole, do kterého píšete, se samo posune do viditelné části obrazovky
// 2.95 - Stylové potvrzovací okno appky místo systémových dialogů (mobilní data, zrušení/nakopnutí pohádky); OPRAVA konzistence vymyšlených postav: zámek vzhledu omylem vyhazoval postavy z příběhu (Otesánek…) — teď v něm zůstávají a Claude jim musí psát plný popis (co to je, barvy, velikost) → stejná podoba na všech stránkách
// 2.94 - Panel 💰 Spotřeba nově počítá Gemini a hlas: appka si po každé pohádce zapíše počet obrázků a znaků (usage/ v Blobu) — „🎨 Gemini: N obrázků ≈ $ ≈ Kč" a „🎙️ Namluveno ~N znaků" za 30 dní; ElevenLabs kredity se ukážou po povolení oprávnění User→Read u API klíče
// 2.93 - Panel čtečky vyjíždí zpoza spodní hrany (na výšku) / pravé hrany (na šířku) s plynulým efektem — obraz se už nezmenšuje; mazání: po odjištění zmizí vlastní 🗑️ a ▶ (konec dvou košů) + nápověda „přejeďte doleva pro smazání"
// 2.92 - Pozadí v2: každý svět je celá nová ilustrace s Nicoláskem a Valentýnkou (podle fotek), stará grafika se skryje; výběr světa velkým tlačítkem s rolovací nabídkou; ovládání čtečky nikdy nepřekryje obrázek (při otevření panelu se obraz plynule zmenší); ikona otočení = ležatý/stojící telefon; hudební podkres se ztiší pod hlasem a vrací se mezi scénami (ducking)
// 2.91 - Ovládání čtečky předěláno: jen 4 velká tlačítka (Přehrát/Pauza, Strana, Na šířku, Domů) — v portrétu jedna řada na šířku obrázku dole, ve fullscreenu jeden sloupec na výšku obrázku vpravo; tlačítka Hlas a Hudba se nastavují v hlavním menu, auto-přechod scén je zapnutý vždy
// 2.90 - Ovládání čtečky je decentní: kompaktní tmavý panel (na výšku dole ve 2 sloupcích, na šířku úzký sloupek u kraje), nepřekrývá obrázek, objeví se jen ťuknutím na displej a po 5 s sám zmizí
// 2.89 - Oprava swipe mazání: po swipu už se omylem nespustí pohádka (potlačení syntetizovaného kliku, stav v ref); odjištěná položka má neprůhledné pozadí — červené Smazat neprosvítá skrz text
// 2.88 - Vision QA: každý vygenerovaný obrázek automaticky zkontroluje kontrolní model (dvojitá postava, cizí lidé, špatné vlasy/oblečení, anatomie) a vadný se JEDNOU překreslí s popisem chyby; do zámku přidáno „každá postava přesně jednou" (konec dvou tatínků)
// 2.87 - Nový ovládací panel čtečky: moderní tlačítka přes celou šířku s popiskem (Přehrát, Auto, Hlas, Hudba, Na šířku, Domů — viditelné i na výšku, panel jde rolovat); otočení jedním ťuknutím (tlačítko se řídí skutečným stavem fullscreenu); Domů vždy ukončí fullscreen — home screen už nebude obrovský na šířku
// 2.86 - Displej při čtení pohádky nezhasíná (Wake Lock — drží se, dokud je otevřená čtečka, obnoví se po návratu do appky); rolující titulky: začátek i konec věty jsou plně čitelné (vnitřní odsazení textu větší než vyblednutí okrajů)
// 2.85 - Hlubší a dramatičtější příběhy (přímá řeč ve scénách, pocity hrdinů, skutečná sázka, temný okamžik před rozuzlením); dlouhé názvy v Posledních pohádkách rolují tam a zpět (čitelné celé); stylové mazání: swipe doleva nebo ťuknutí na 🗑️ odhalí červené Smazat — konec systémového dialogu
// 2.84 - Pravidla konzistence (PRAVIDLA-KONZISTENCE.md): vzhled postav je KANONICKÝ — po napsání příběhu se popis vzhledu serverově přepíše doslovnými popisy z kartotéky (konec „jednou blond, podruhé hnědé"); převleky jen přes zamčený záznam Story outfits; anatomie natvrdo (přesně 2 ruce, 2 nohy, 5 prstů, kolo má 2 kola)
// 2.83 - Inspirační fotky u pole přání (📷 Foto) zvednuty ze 3 na 8 — sjednoceno s fotkami vlastního světa
// 2.82 - Vlastní svět pohádky unese až 8 fotek (dřív 1): mřížka náhledů s mazáním ×, vícenásobný výběr najednou, všechny fotky jdou Claudovi jako inspirace; staré světy s jednou fotkou fungují dál
// 2.81 - Konzistence a kvalita obrázků: primární malíř zpět gemini-3.1-flash-image (2.5 jen záloha při kvótě); styl natvrdo 2D malovaná ilustrace (zákaz 3D renderu, fotorealismu i podpisů); sportovní vybavení (kolo!) a sportovní oblečení se zamyká jako Key object — stejný typ, barvy i dres v každé scéně
// 2.80 - Příběhy píše Claude Sonnet místo Opusu (kvalita pohádek srovnatelná, ~5× levnější psaní); jde přebít proměnnou ANTHROPIC_MODEL_PRIMARY
// 2.79 - Levnější kreslení: primární obrázkový model je gemini-2.5-flash-image (~0,90 Kč/obrázek, −42 %), dražší gemini-3.1-flash-image (~1,55 Kč) zůstává jen jako záloha při vyčerpání denní kvóty; jde přebít proměnnou GEMINI_IMAGE_MODEL_PRIMARY
// 2.78 - Strop automatických oživení: pohádka bez posunu se oživí max 4×, pak se zastaví s chybou („zastaveno, ať se nepálí kredit") — každé oživení překresluje scény a stálo peníze; posun vpřed počítadlo nuluje
// 2.77 - Ochrana denní kvóty Gemini (1000 obrázků/den/model): při stropu se pokusy neopakují, automaticky se zkusí záložní model (gemini-2.5-flash-image → kapacita 2×), a když je na stropu i ten, pohádka se okamžitě zastaví s jasnou chybou; nakopnutí po resetu naváže na hotové scény (nepíše ani nekreslí znovu)
// 2.76 - Když Gemini nekreslí (vyčerpaná kvóta, billing…), appka ukáže důvod přímo pod tlačítkem („🎨 Obrázky hlásí chybu: Gemini 429…") místo věčných přesýpacích hodin; pohádka bez jediného obrázku skončí viditelnou chybou, ne prázdnou knížkou
// 2.75 - Křížek ✕ v rohu dílů tlačítka fronty: zaseknutou/chybovou pohádku zruší jedním ťuknutím (smaže i data na serveru); zdravě běžící se 1× zeptá, ať ji děti nezruší omylem
// 2.74 - 📜 České pohádky: rolovací seznam 28 licenčně volných klasik (lidové, Erben, Němcová, Grimmové, Andersen, Perrault) — vybraná pohádka funguje jako svět, příběh se odehraje s vašimi hrdiny; 🎲 námět i auto pozadí ji respektují
// 2.73 - Aplikace se otevírá vždy do hlavního menu — rozečtená pohádka už nenaskočí přes celou obrazovku, zůstává načtená pod formulářem (▶ ji otevře ve čtečce)
// 2.72 - 🎲 Vymysli námět respektuje vybraný svět pohádky a zaškrtnuté postavy (a staví na už napsaném textu); u vlastního světa nové tlačítko 🧠 Nastuduj svět — z popisu nebo vloženého internetového odkazu Claude sestaví průvodce světem (postavy, vzhled, atmosféra), a když mu něco chybí, položí doplňující otázku
// 2.71 - Pod počtem stránek se ukazuje orientační délka čtení: „🕐 cca X min čtení (1 stránka ≈ půl minuty)", přepočítává se hned při změně počtu
// 2.70 - Počet stránek se místo posuvníku (šlo o něj omylem zavadit) nastavuje tlačítky − a + po stranách čísla; drží meze 3–20
// 2.69 - Tlačítko 🧹 Smazat text u pole přání (objeví se, jen když v poli něco je); živější přednes hlasu (voice_settings: víc intonace a dramatičnosti); zvířecí zvuky se píší foneticky a protaženě („Haf haf!“, „Mňauuu…“), ať je vypravěč zahraje; česká výslovnost jmen — do TTS jde Nikolásek/Džejms/Árčí (titulky zůstávají s původním pravopisem)
// 2.68 - Pozadí aplikace jsou teď ilustrace ve stylu pohádek: maluje je Gemini (stejný styl jako obrázky scén), každý z 9 světů se vygeneruje jen jednou a uloží na server (backgrounds/); než se stáhne, drží barevný gradient z v2.67
// 2.67 - Přepínatelné pozadí aplikace: 9 světů (noc, les, hory, vesmír, džungle, moře, závody, pouť, kouzlo) malovaných v CSS; tlačítko 🎨 vlevo nahoře jimi roluje, režim Auto přepne pozadí samo podle zvoleného tématu pohádky (vlastní svět = ✨ kouzlo); volba se pamatuje
// 2.66 - Anglické názvy postav v EN verzi (Dad Jan, Mom Jana, Archie the dog…) v chipech i vyprávění; tlačítko 🎲 Vymysli námět (Claude navrhne zápletku do pole přání); vlastní svět pohádky podle fotky nebo popisu — chip „+ Vlastní svět", uložené světy se dají znovu použít i smazat
// 2.65 - Titulky na šířku: text jede synchronně s hlasem (řízeno pozicí v nahrávce, pauza text zastaví), vnitřní okraje rámečku + měkké vyjíždění textu na krajích; rámeček zůstává na šířku obrázku
// 2.64 - Oprava: dlouhý název pohádky vytlačoval tlačítka 🗑️ a ▶ mimo displej (grid minmax(0,1fr) + zkrácení názvu trojtečkou)
// 2.63 - Mazání pohádek z historie: ikona 🗑️ u každé položky (s potvrzením) — smaže pohádku z telefonu vč. offline dat a uvolní místo
// 2.62 - Věrnější táta Jan: nová detailní fotka obličeje jako druhá reference pro Gemini + přesnější popis (vysoké čelo, krátké tmavě hnědé vlasy, strniště, hnědé oči); podpora více referenčních fotek na postavu
// 2.61 - Oprava „blob-write-failed: invalid header value": Blob token se čistí (uvozovky, nové řádky, smetí z Quickstartu) — z hodnoty se vytáhne jen samotný vercel_blob_rw_… token
// 2.60 - Server už nehromadí hotové pohádky (jsou v telefonu): po stažení se serverová data pohádky mažou okamžitě, úklid chrání jen běžící joby (+1h lhůta), běží 1× za hodinu — bezplatný 1GB Blob se už nezaplní; důvod selhání startu se zobrazí (Server: blob-write-failed…)
// 2.59 - Diagnóza mrtvých startů: start jobu zapíše stav SYNCHRONNĚ — když Blob zápis selže (plné úložiště / token), vrátí se viditelná chyba místo zombie jobu; úklid úložiště běží i při startu aplikace (1× za 6 h) a maže osiřelé joby starší 3 h
// 2.58 - Záchrana zaseknutých pohádek: job, který na serveru nikdy nezapsal stav (404), se automaticky oživí přes /continue nebo po 5 min ukončí chybou; zaseknutý díl tlačítka červeně pulzuje s ⚠️ — ťuknutím nakopnete, podruhé odeberete z fronty
// 2.57 - Offline zásoba rozšířena na 20 pohádek (localStorage/IndexedDB/Blob drží posledních 20; žádost o trvalé úložiště, ať prohlížeč cache nemaže); upozornění před generováním na mobilních datech (~30 MB, potvrzení 1× za sezení)
// 2.56 - Ťuknutí na díl tlačítka (1./2./3.) přepne kartičky na průběh té konkrétní pohádky; zvolený díl je zvýrazněný bílým rámečkem
// 2.55 - Fronta bez bublinek: velké tlačítko se rozdělí na části — jedna část na pohádku (✍️ píše se / 🎨 x/y s plnícím se pruhem / ▶ Otevřít / ⚠️ chyba); plovoucí bublinky z hlavní obrazovky zmizely
// 2.54 - Oprava zaseknutého „Píšu novou pohádku": kratší imagePrompty (popis postav se do obrázků vkládá automaticky, nekopíruje se 20×) → psaní 20stránkové pohádky se vejde do 5min limitu; retry při zahlcení Claude API (429); popisek, že kartičky ukazují nejnovější pohádku
// 2.53 - Při čtení pohádky se neukazují bublinky průběhu dalších pohádek — průběh a tlačítko Otevřít uvidíte po návratu Domů
// 2.52 - Čtečka na PC a tabletu přes CELOU obrazovku (zrušen limit šířky 860 px v reader módu; formulář zůstává úzký)
// 2.51 - Oprava Spotřeby: částky z Anthropic API jsou v centech (ukazovalo 100× víc), přepočet na Kč kurzem ČNB; srozumitelná hláška, když ElevenLabs klíč nemá oprávnění číst účet
// 2.50 - Chybová hláška jde zavřít křížkem ✕ (dřív zůstávala až do dalšího pokusu)
// 2.49 - Přehled 💰 Spotřeba: skutečná útrata za Claude (Admin API, celý účet, posledních 30 dní) a stav kreditů ElevenLabs přímo v aplikaci; Gemini jen odkazem (Google útratu přes API nevydává)
// 2.48 - Spolehlivější start serverové výroby (fronty): 2 pokusy s timeoutem 30 s místo jednoho s 15 s, server odpovídá okamžitě (zápis zadání do Blobu až po odpovědi) — méně pádů do lokálního generování bez fronty
// 2.47 - Automatický úklid Blob úložiště: po dokončení pohádky se smažou serverová data jobů, které vypadly z historie posledních 10 pohádek (běžící a čerstvé joby <24 h se nikdy nemažou)
// 2.46 - Fronta pohádek: až 3 pohádky se připravují najednou na serveru — další jde zadat hned, bez čekání; každá má vlastní řádek s průběhem a tlačítkem Otevřít, kartičky ukazují tu nejnovější
// 2.45 - Až 20 stránek: navazovací serverový job (po 5min limitu Vercelu automaticky pokračuje endpointem /api/job/continue — zdarma, bez Pro plánu); delší příběhy od Clauda (16k tokenů); rychlejší načtení — hotové scény se stahují do telefonu průběžně už během výroby a kartičky ukazují skutečné náhledy
// 2.44 - Fix „nabídka zmizela": rozepsaný draft bez obrázků už neotevře prázdnou temnou čtečku (obnova jen s kompletními obrázky + pojistka: čtečka bez pohádky → návrat na formulář); stažení hotové pohádky ze serveru s retry a placeholderem; otevřený panel ovládání už nepřekrývá toast průběhu
// 2.43 - Serverové generování na Vercelu: pohádka se připraví na serveru (Blob), telefon jen sleduje stav a stáhne výsledek — přepnutí appky nevadí; bez Blob tokenu automatický fallback na lokální generování
// 2.42 - Kotevní obrázek: scéna 1 se generuje první a její obrázek je vizuální referencí pro všechny další scény — postavy, výšky, styl i předměty (auto) se kopírují z ní
// 2.41 - Animace „Píšu příběh": píšící tužka ✍️, blikající tečky, výraznější a rychlejší shimmer
// 2.40 - Key objects lock (auto a předměty stejné v celé pohádce); tlačítko 🔄 Na šířku v panelu (fullscreen + orientation lock)
// 2.39 - Konzistence velikostí: povinné 'Heights:' v popisu postav, lock na věk/proporce, sanitizér zachovává výšky; fallback prompt pro blokované scény; poctivý toast při chybějících obrázcích
// 2.38 - Anti-stuck: Wake Lock (displej nezhasne při generování), hlídač zaseknutí (2,5 min bez pokroku → tlačítko Pokračovat), auto-obnovení při návratu do zamrzlé záložky
// 2.37 - Odolné generování: job se pamatuje (text i obrázky), auto-resume po restartu; průběžné cachování scén; až 3 verifikační kola — pohádka není hotová, dokud nejsou všechny obrázky
// 2.36 - Nové referenční postavy: James (6, nejlepší kamarád z Riverside) a Bella (8, Jamesova sestra) s fotkami
// 2.35 - Rodinné referenční fotky: táta Jan, máma Jana, pes Archie (nová postava), Valentýnka — Gemini nyní dostává fotky a kreslí podle skutečné podoby
// 2.34 - Panel přikotven dole; šipky integrované do obrázku (střed, jeho okraje); Recent stories přesunuty pod pohádku
// 2.33 - Anglické názvy témat (Story world) při EN; vlastní postavy se ukládají (localStorage) — zůstávají do smazání ×, pohádky s nimi zůstávají v historii
// 2.32 - Jednotná velikost obrázků: Gemini generuje 16:9 (imageConfig), zobrazení v pevném 16:9 rámu (cover) v obou orientacích
// 2.31 - Portrait reader: text box přímo pod obrázkem, ovládací panel pod textem (jako v landscape); toggle panelu ťuknutím kamkoli na kartu
// 2.30 - Hudba defaultně vypnutá; titulky ukazují skutečné modely (API /api/models); mluvené „Dobrou noc, Nicolásku a Valentýnko" na konci titulků
// 2.29 - Přepínač jazyka UI 🇨🇿/🇬🇧: celé rozhraní česky nebo anglicky, volba se pamatuje, EN auto-vybere anglického vypravěče
// 2.28 - Text na bílém podkladu: portrait celý text bez rolování, landscape bílý jednořádkový ticker
// 2.27 - Ticker jen pod šířkou obrázku; play z hlavní obrazovky → reader mód; replay z historie auto-přehraje; manifest bez orientation (rotace dle systému)
// 2.26 - Fix hlas (payload bez obrázku + odblokování play); šipky skryté i v portrait (jen s panelem); play zavře panel + restart rollingu; PWA manifest (fullscreen po přidání na plochu)
// 2.25 - Automatická přestavba při otočení: layout + restart rolování textu (portrait ⇄ widescreen)
// 2.24 - Widescreen: bez nadpisu, text = jednořádkový horizontální ticker dole, šipky jen s panelem (odsazené); obraz ~90 % výšky
// 2.23 - Titulky v malém okně POD obrázkem (nepřekrývají obraz), auto-rolling; panel dole (portrait) / vpravo (landscape); fix výšky v landscape
// 2.22 - Imerzní čtečka: obraz přes celý screen, text jako titulky dole (scrolluje, nikdy nepřeteče), ovládání skryté — ťuknutí zobrazí panel vpravo, šipky plovoucí po stranách
// 2.21 - Šířka: full-width obraz na mobilu, tablet/landscape = obraz vedle textu; velká tlačítka přes celý panel; vlajka hlasu (🇨🇿/🇬🇧); play už neukazuje ⏳ při přepnutí hlasu
// 2.20 - Reader: obraz bez ořezu/deformace (contain, kino styl), text scrolluje; pryč Nová pohádka; popisky pod tlačítky; auto-kontrola + oprava chybějících obrázků; 2 scény paralelně; progres i pro bg pohádku
// 2.19 - Reader mode: book vyplní viewport bez edge-to-edge; šipky ← → přesunuty pod kartu (žádné ořezání)
// 2.18 - Detekce přerušeného spojení (přepnutí appky): česká hláška + tlačítko Zkusit znovu; timeout 90s na scene fetch
// 2.17 - Odstraněn reader mode (žádný fullscreen); pohádka se zobrazí pod formulářem s auto-scroll; popis kroků generování
// 2.16 - Odstraněno expand-on-play (CSS position:fixed overlay při ▶); čistý reader mód bez přepínání
// 2.15 - Expand on play: ▶ roztáhne book přes celý viewport (CSS position:fixed, bez native fullscreen)
// 2.14 - Reader: max screen (edge-to-edge, skrytý back-btn, kompaktní titulek); konzistence postav: APPEARANCE LOCK v Gemini i Claude
// 2.13 - Tlačítko Vytvořit pohádku: animovaný progress fill + %; gen-cards pod tlačítkem; odstraněno Zpět na pohádku
// 2.12 - Odstraněn fullscreen mód; oranžové šipky ← → pro navigaci scén
// 2.11 - Gen-cards od začátku načítání; oranžové tlačítko 🏠 v ovládání; oranžové tlačítko Zpět na pohádku
// 2.10 - Fullscreen: image 16:9 (no crop), text pod ním; fix text overflow; témata: Pokémon + Sonic
// 2.9 - Reader mode: viewport-filling layout (CSS Grid 1fr na book-card), image vyplní zbývající výšku
// 2.8 - Fullscreen: tap-to-show ovládání (controls skryty, zobrazí se na klik/tap na 3s, pak zmizí)
// 2.7 - Fullscreen: CSS Grid (1fr auto auto auto) na book-card → controls vždy viditelné; 16:9 aspect-ratio v reader; audio optional
// 2.6 - Historie: výrazné karty s offline/size/scény badge, tlačítko → oranžový % bar + ikonky scén
// 2.5 - Fullscreen: obraz dostane explicitní height:65dvh (bez flex chain), draft pohádky do localStorage při přepnutí okna
// 2.4 - Fullscreen: .book dostane position:fixed inset:0 z-index:10 — bypasses flex chain, viewport height garantována
// 2.3 - Fullscreen: wrapper-div + position:absolute inset:0 pro obraz (grid 1fr nefungoval s flex-allocated height v Chrome Android)
// 2.2 - Konzistence postav: silnější Gemini prompt (zákaz extra postav, fixní vlasy+oblečení), Claude kopíruje popis doslova
// 2.1 - Fullscreen: okamžité nastavení CSS třídy (iOS + Android fix); Cache: vždy ukládat i při chybě audia; bookReady = obrazky stačí
// 2.0 - Verze badge, fix historie během bg generování, IndexedDB cache cross-session
// 1.9 - IndexedDB cache pro pohádky z historie (přežije restart PWA)
// 1.8 - Fullscreen opravy: správný flex chain, ctrl-fullscreen rozměry, aspect-ratio fix
// 1.7 - Fullscreen mód (⛶), swipe slidy, tečky uvnitř karty
// 1.6 - Paralelní generování + sledování starší pohádky, cache scén v paměti
// 1.5 - Reader mód (celá obrazovka pro pohádku), auto-fullscreen při spuštění
// 1.4 - Oprava 504 timeoutu pro 15 scén, hudební tlačítko v formuláři
// 1.3 - Rolling credits po dokončení pohádky
// 1.2 - ElevenLabs hlas, výběr vypravěče
// 1.1 - Gemini ilustrace, background music
// 1.0 - Základní verze: Claude + generování pohádek
